### ISSUE TITLE
Broken markdown

### ISSUE THREAD

**Issue by jtyr** [takezoe/gitbucket#210]
If I create a README.md with the following content:

---[ README.md START]---
```
cd /tmp
mkdir aaa
cd aaa
```
---[ README.md END]---

it shows the code block as one line.

**Comment by takezoe** [comment]
We will switch markdown processor to [markedj](https://github.com/gitbucket/markedj) from pegdown in GitBucket 3.7. Almost markdown syntax issues will be solved by markedj.

**Comment by takezoe** [comment]
Merged with #912
