### ISSUE TITLE
BugsEverywhere integration?

### ISSUE THREAD

**Issue by smoyer64** [takezoe/gitbucket#366]
I use [BugsEverywhere](http://www.bugseverywhere.org/) for distributed issue tracking and I'm close to completing a Java interface to the underlying system.  It appears that issue tracking within GitBucket is broadly compatible with the BugsEverywhere format ... would anyone else be interested in seeing the database issue tracking replaced by distributed issue tracking?  What about a pluggable system where you could choose between back-end issue tracking systems?

**Comment by smoyer64** [comment]
Is there any documentation for using the plug-in system?  How much of it is in place?  Is it stable?  Has anyone actually used it for an integration?

I'd be happy to give it a try but would find it much easier with an example.

Thanks!

**Comment by takezoe** [comment]
@smoyer64 Sorry. We've never provided stable plugin system. Current plugin system is experimental and it will be once removed in the next release. We are continuing consideration about the plugin system.

**Comment by smoyer64** [comment]
Okay ... you answered my real question even though I wasn't very clear about what I was asking!  I'm still interested in the plug-in system but obviously I won't develop anything against the version you've deprecated.  Is there another feature request that's still open for a plug-in system or is this simply in your mental road map?

I should also note that I have a few users who are very happy with GitBucket ... Thanks for all the hard work you've put into this system!
