### ISSUE TITLE
how do I turn on logging?

### ISSUE THREAD

**Issue by fomcl** [takezoe/gitbucket#371]
Hi,

First off: compliments for Gitbucket. Really great job! Yesterday we were configuring LDAP so we wanted to turn on logging (and possibly set the logging level). How can this be done, and where are the logs written?

Thanks a lot!

Albert-Jan
Netherlands

**Comment by takezoe** [comment]
Close all questions. If you have any questions about GitBucket, please send them to [the gitter room](https://gitter.im/takezoe/gitbucket) instead of issue according to [the Guideline for Issues](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md).
