### ISSUE TITLE
Line selecting bugs

### ISSUE THREAD

**Issue by maliayas** [takezoe/gitbucket#388]
1. It causes text selection with the shift click.

    ![ekran grnts 2014 05 31 11_21_11](https://cloud.githubusercontent.com/assets/844008/3138574/96b7a772-e89c-11e3-8a57-2f3f61c01318.png)

2. Pressing high number first doesn't work.

3. Pressing the number shouldn't move the viewport to there. I.e. no automatic scroll should happen.

P.S. I'm using firefox.

**Comment by takezoe** [comment]
@maliayas It's not a bug.

- At first, click line number **without shift**
- Second click higher number with shift
