### ISSUE TITLE
Providing JSON style API

### ISSUE THREAD

**Issue by masao-kunii** [takezoe/gitbucket#41]
like GitHub.
http://developer.github.com/

Especially about issues because one of Github problems is poor issues management. The API will make up for it and enable cooperate with other systems.

**Comment by tanacasino** [comment]
refs #603

**Comment by takezoe** [comment]
@tanacasino Some APIs have been added by #610 and #635. So should I close this issue? Will these APIs come with 3.1?

**Comment by tanacasino** [comment]
@takezoe 
Yes, some APIs are available in 3.1.
And I will continue to add other APIs for the future release.
