### ISSUE TITLE
Why is commit count limited to 10001?

### ISSUE THREAD

**Issue by agr1277** [takezoe/gitbucket#440]
Just wondering why this, seemingly arbitrary number, is the limit for the commit count.

Thanks.

**Comment by takezoe** [comment]
Close all questions. If you have any questions about GitBucket, please send them to [the gitter room](https://gitter.im/takezoe/gitbucket) instead of issue according to [the Guideline for Issues](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md).
