### ISSUE TITLE
gitbucket is slow

### ISSUE THREAD

**Issue by Centaur** [takezoe/gitbucket#441]
We throw gitbucket.war into tomcat on one of our servers. This app is obviously slower than others in the same tomcat instance, every click seems cost 1+ second to respond.

**Comment by nazoking** [comment]
I think, acitivity table is too large.
My gitbucket server has 377 reposotory, 21577 activity from 2013-10-28 08:52:43.768.
ActivityService.getRecentActivities query (that is used in the top page), take 15945 ms until the end .

**Comment by takezoe** [comment]
It might be to delete the old activity records automatically.

**Comment by takezoe** [comment]
We will add a new configuration item to specify limit of activity logs in GitBucket 3.2. If your activity table is too large, please configure it at the system settings console.

**Comment by takezoe** [comment]
Fixed in #732

**Comment by MarcusMoeller** [comment]
Could you please tell me which value this is? Is it the number of recent activity items displayed on the dashboard? What is a good value ? e.g. 10, 100 ?
