### ISSUE TITLE
show compare/pull request link near branch link.

### ISSUE THREAD

**Issue by nazoking** [takezoe/gitbucket#442]
it is very useful.

on branches page
![branches](http://i.gyazo.com/e3e0c296c9368899a4a46368d81767bd.png)

on tree page
![branch select](https://cloud.githubusercontent.com/assets/18655/3672090/816c3fb8-1259-11e4-8f95-5441d8ba2543.png)
![pull request](http://i.gyazo.com/1da03cf143ae39838f29fcac21913db1.png)

**Comment by takezoe** [comment]
Fixed in #611
