### ISSUE TITLE
Not able to login persistently on Firefox

### ISSUE THREAD

**Issue by hrj** [takezoe/gitbucket#469]
In a local instance, I am able to login correctly using Chromium version 36.

But I am not able to login using Firefox 31.0. The password gets accepted and lasts for one-screen. But as soon the second page is navigated to, it asks for the sign-in form again.

Are the login cookies being set through some funky mechanism? I am using NoScript in Firefox. I am also using HTTPSwitchBoard in Chromium.

**Comment by takezoe** [comment]
@hrj Do you still have this problem?

**Comment by hrj** [comment]
It is working fine now with gitbucket v 2.7 and Firefox 34.
:+1:
