### ISSUE TITLE
Apach proxy error occured, when existing big diff between branches.

### ISSUE THREAD

**Issue by kurofune** [takezoe/gitbucket#479]
GitBucket2.2.1 is running on Tomcat8 via Apache2.2.15 on CentOS6.5.

I want to create new pull request.
But Apach proxy error occured when opening diff page.
I thought that the cause is existing too many (about 1500) commit between branches.

browser say

```
Proxy Error
The proxy server received an invalid response from an upstream server.
Reason: Error reading from remote server
```

**Comment by takezoe** [comment]
Merged with #907
