### ISSUE TITLE
data.h2.db file locked when upgrading from Gitbucket 2.2 to 2.3

### ISSUE THREAD

**Issue by hanxue** [takezoe/gitbucket#493]
I am running the following:

```
Gitbucket: 2.2.1
OS: Windows 7 64bit
Java: OpenJDK 1.7.0-67
Java Web Container: Jetty 8.1.9
```

To upgrade,

1. Download the latest gitbucket.war 2.3 release
2. Stop existing jetty process
3. Run jetty process with command line pointing to gitbucket.war v2.3

When I access GitBucket, I see error 500. Running jetty manually produce the following error
```
org.h2.message.DbException: IO Exception: "java.io.IOException: The process cann
ot access the file because another process has locked a portion of the file"; "C
:/Users/ep/.gitbucket/data.h2.db" [90031-180]
```
Full stack trace available at https://gist.github.com/anonymous/26b52aee04d7fa214f7f

This is odd because I have terminated all java.exe (Jetty) processes, before starting up Jetty again with the upgraded Gitbucket war. I manage to replicate the error when I stop and start the process. The error mysteriously went away just when I fire up `ProcMon` to try to identify what is locking the H2 database file.

**Comment by takezoe** [comment]
Out of date
