### ISSUE TITLE
New issue comment creation fails silently

### ISSUE THREAD

**Issue by pimpedoutgeek** [takezoe/gitbucket#521]
* According to our gitbucket administrator when asked if attemps to create new comments in an existing issue are failing fetched the reply gitbucket is failing silently.
* If there is a limit on the number of comments per issue it is not evident that creating a new issue comment once the limit has been reached is in itself an issue.
* Issue tracker comments should be unlimited or at least extendable or minimally some type of failure notification.

**Comment by takezoe** [comment]
Out of date
