### ISSUE TITLE
Performance is bad when navigating a large project in the dashboard page

### ISSUE THREAD

**Issue by KenLau** [takezoe/gitbucket#535]
Hey guys, our company have launched a gitbucket service with version 2.1, i found that there is a performance problem in gitbucket 2.1, whenever i navigate a large project in the dashboard page, it takes a very long time to finish loading the corresponding directory page, have you done anything about this performance issue since 2.1? or else, do you have any plan to improve it? thank you very much!

**Comment by takezoe** [comment]
I expect a lot of activities are causing performance problem. However recent versions of GitBucket can delete old activities by configuration. Please try it.
