### ISSUE TITLE
Markdown makes extra paragraphs

### ISSUE THREAD

**Issue by mslinn** [takezoe/gitbucket#539]
The GitHub and BitBucket markdown processor only creates a new paragraph after a blank line. However, gitbucket makes a new paragraph after every newline. For example, imagine that the following lines were not surrounded by quad-quotes; GitHub and BitBucket would display these as one paragraph:

````
This
should
be one
paragraph
````

**Comment by takezoe** [comment]
I expect this problem will be fixed in GitBucket 3.7 by new markdown processor [markedj](https://github.com/gitbucket/markedj).
See also #912.
