### ISSUE TITLE
Wiki page return internal error in Gitbucket 2.5

### ISSUE THREAD

**Issue by tune** [takezoe/gitbucket#542]
When I use Gitbucket 2.5 Wiki top page in certain project return internal error, though same markdown is displayed correctly in Gitbucket 2.4.1.

My gitbucket is running on Tomcat7, and I've checked tomcat7 roughly.
But I couldn't find any particular gitbucket error message there.

Is there a good way to investigate this problem?
Unfortunately I cannot share the wiki page content itself since it's confidential one.

**Comment by takezoe** [comment]
Out of date
