### ISSUE TITLE
github pull request builder pluing

### ISSUE THREAD

**Issue by nazoking** [takezoe/gitbucket#545]
I want to use jenkins github pull request builder pluing.
https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin
https://github.com/janinko/ghprb

Maybe it is necessary to implement the following features..

* more web hook events.
  * pull_request
    * action=opened/reopened/synchronize
  * issue_comment
* API v3
  * Pull Requests https://developer.github.com/v3/pulls
    * Get a single pull request
    * Update a pull request ( state to close )
  * Issues/Comments https://developer.github.com/v3/issues/comments/
    * Create a comment
  * Repositories/Statuses https://developer.github.com/v3/repos/statuses/
    * Create a Status
  * Repositories/Webhooks https://developer.github.com/v3/repos/hooks/
    * List hooks
    * Create a hook
    * (If the user is registered manually, you may not need to implement this function)

**Comment by cvrebert** [comment]
X-Ref: #41

**Comment by tanacasino** [comment]
merged!
