### ISSUE TITLE
Add backup functionality from the admin UI

### ISSUE THREAD

**Issue by werne** [takezoe/gitbucket#575]
Please add backup 'trigger' functionality from the GUI.
H2 has the command:

```backup to 'backup-h2-datexxx.zip'```
that can be executed while the DB is running.
The same thing would be needed for the part of GitBucket specific files, e.g. everything required to a 
zip.

tnx.

**Comment by just1689** [comment]
I second that

**Comment by rlazoti** [comment]
:+1

**Comment by frankhommers** [comment]
:+1:

**Comment by frederic-meyrou** [comment]
Hi mates,

Any news for this very awaited feature?! :)
Tks a million.

./Fred

**Comment by takezoe** [comment]
[gitbucket-h2-backup-plugin](https://github.com/McFoggy/gitbucket-h2-backup-plugin) is available for this purpose.
