### ISSUE TITLE
Updating 2.6 to 2.7 on tomcat7: works only if servlet container restarts.

### ISSUE THREAD

**Issue by naqern** [takezoe/gitbucket#583]
I had a working 2.6 installation. After substitution of the war file on the tomcat7 container the servlet failed to start. 
I downgraded back to 2.6 but got the same error. 
So I upgraded again to the 2.7, the servlet works only after "service tomcat7 stop" + "service tomcat7 start". Without the stop+start, the release 2.7 fails to start (just as a further test I tried the 2.6 and the behaviour is the same: it starts only after a container stop+start); this is the catalina.out:

> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/var/lib/tomcat7/webapps/gitbucket/WEB-INF/lib/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/var/lib/tomcat7/webapps/gitbucket/WEB-INF/lib/slf4j-jdk14-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
> 04:33:12.245 [http-bio-8080-exec-101] INFO  org.quartz.impl.StdSchedulerFactory - Using default implementation for ThreadExecutor
> 04:33:12.251 [http-bio-8080-exec-101] INFO  org.quartz.simpl.SimpleThreadPool - Job execution threads will use class loader of thread: http-bio-8080-exec-101
> 04:33:12.268 [http-bio-8080-exec-101] INFO  o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
> 04:33:12.268 [http-bio-8080-exec-101] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.2.1 created.
> 04:33:12.269 [http-bio-8080-exec-101] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
> 04:33:12.270 [http-bio-8080-exec-101] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.2.1) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
>   Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
>   NOT STARTED.
>   Currently in standby mode.
>   Number of jobs executed: 0
>   Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
>   Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.
> 
> 04:33:12.270 [http-bio-8080-exec-101] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
> 04:33:12.270 [http-bio-8080-exec-101] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler version: 2.2.1
> 04:33:12.551 [http-bio-8080-exec-101] INFO  o.scalatra.servlet.ScalatraListener - The cycle class name from the config: ScalatraBootstrap
> 04:33:12.591 [http-bio-8080-exec-101] INFO  o.scalatra.servlet.ScalatraListener - Initializing life cycle class: ScalatraBootstrap
> Dec 30, 2014 4:33:13 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
> Dec 30, 2014 4:33:13 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/gitbucket] startup failed due to previous errors
> 04:33:13.357 [http-bio-8080-exec-101] INFO  o.scalatra.servlet.ScalatraListener - Destroying life cycle class: ScalatraBootstrap
> 04:33:13.357 [http-bio-8080-exec-101] INFO  org.quartz.core.QuartzScheduler - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED shutting down.
> 04:33:13.358 [http-bio-8080-exec-101] INFO  org.quartz.core.QuartzScheduler - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED paused.
> 04:33:13.358 [http-bio-8080-exec-101] INFO  org.quartz.core.QuartzScheduler - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED shutdown complete.
> Dec 30, 2014 4:33:13 AM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/gitbucket] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
> Dec 30, 2014 4:33:13 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/gitbucket] appears to have started a thread named [DefaultQuartzScheduler_Worker-1] but has failed to stop it. This is very likely to create a memory leak.
> Dec 30, 2014 4:33:13 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/gitbucket] appears to have started a thread named [DefaultQuartzScheduler_Worker-2] but has failed to stop it. This is very likely to create a memory leak.
> Dec 30, 2014 4:33:13 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/gitbucket] appears to have started a thread named [DefaultQuartzScheduler_Worker-3] but has failed to stop it. This is very likely to create a memory leak.
> Dec 30, 2014 4:33:13 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/gitbucket] appears to have started a thread named [DefaultQuartzScheduler_Worker-4] but has failed to stop it. This is very likely to create a memory leak.
> Dec 30, 2014 4:33:13 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/gitbucket] appears to have started a thread named [DefaultQuartzScheduler_Worker-5] but has failed to stop it. This is very likely to create a memory leak.
> Dec 30, 2014 4:33:13 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/gitbucket] appears to have started a thread named [DefaultQuartzScheduler_Worker-6] but has failed to stop it. This is very likely to create a memory leak.
> Dec 30, 2014 4:33:13 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/gitbucket] appears to have started a thread named [DefaultQuartzScheduler_Worker-7] but has failed to stop it. This is very likely to create a memory leak.
> Dec 30, 2014 4:33:13 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/gitbucket] appears to have started a thread named [DefaultQuartzScheduler_Worker-8] but has failed to stop it. This is very likely to create a memory leak.
> Dec 30, 2014 4:33:13 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The webSLF4J: Class path contains multiple SLF4J bindings.

**Comment by neandrake** [comment]
I used tomcat 7 to undeploy 2.7 and re-deploy 2.8. It was unable to startup again. Looking through the logs, the database file was locked by the tomcat process. Undeploying the servlet was not enough to free the database file so I had to stop and start tomcat in order for the new deploy of 2.8 to work.

**Comment by takezoe** [comment]
@neandrake Yes, shutdown Tomcat at first to upgrade GitBucket.
