### ISSUE TITLE
Unable to download the file

### ISSUE THREAD

**Issue by ynnuyonw** [takezoe/gitbucket#588]
http://gitbucket.vicp.net/thok-mc/readme/blob/master/设计规范/.NET设计规范.pdf?raw=true

this request retrun http 500 err.

**Comment by takezoe** [comment]
Could you provide any additional information such as file name, type, size, error message and about your GitBucket environment (e.g. Are you accessing GitBucket directly? or through front server such as Nginx or Tomcat?).

If all files fail to download, I think it's a problem in your environment.

**Comment by ynnuyonw** [comment]
I was in the official Demo, the test is the same.

**Comment by takezoe** [comment]
Merged to #534
