### ISSUE TITLE
Make New Repository visibility default option configurable

### ISSUE THREAD

**Issue by schorsch3000** [takezoe/gitbucket#595]
Hi, i really would like to have the visibility option (public / private) default to private, is there a way to make it configurable?

Thanks Dirk

**Comment by hansgru** [comment]
I don't think this would need to be configurable, but having it default on private would make more sense, since as opposed to GitHub, GitBucket is more for private projects.

**Comment by takezoe** [comment]
Fixed in #602

**Comment by schorsch3000** [comment]
Thanks :+1:
