### ISSUE TITLE
Repo's Disappear upon user being diabled

### ISSUE THREAD

**Issue by phantomofthesoup** [takezoe/gitbucket#601]
Hey, Having an issue where a user was disabled and then when enabled again the repo's disappear entirely.

Is it possible to recover these or have these been deleted forever now?

if so, where can I find them?

thanks

**Comment by takezoe** [comment]
If users disabled once, all related data include repositories are deleted. Unfortunately, you can't recover them forever.

**Comment by phantomofthesoup** [comment]
Thanks for the reply.
