### ISSUE TITLE
How to include images?

### ISSUE THREAD

**Issue by hansgru** [takezoe/gitbucket#622]
How to include images/graphics ?
  - in the readme.md of the project ?
  - in the WIKI documents ?
  - in an arbitrary *.md" file of a project. E.g. /docs/install.md ?

It would be preferable if these images would be "local" to the repo and machine, since "private" repos should work on "intranet only" envs too.

I'm not that much interested in including *.jpeg files (or creating "websites" like github allows), but more augmenting the docs with SVG diagrams.

**Comment by takezoe** [comment]
You can embed the image in the same place as the markdown file in the repository as below:

```
![New GitBucket logo](logo.png)
```

It's also possible in Wiki.

**Comment by hansgru** [comment]
> you can embed the image in the same place as the markdown file

Thank you :).

Is it possible to have them under a sub-directory (to keep some order) ? e.g. (images/logo.png) ?


> It's also possible in Wiki.

but there's no way to upload images in the wiki area using the web UI right now, right? (unlike for issues)

**Comment by takezoe** [comment]
> Is it possible to have them under a sub-directory (to keep some order) ? e.g. (images/logo.png) ?

Yes.

> but there's no way to upload images in the wiki area using the web UI right now, right? (unlike for issues)

Yes. GitHub does not have it. Clone Wiki repository and push images to embed them into Wiki pages.

**Comment by hansgru** [comment]
> Clone Wiki repository and push images to embed them to Wiki pages.

This might be worth mentioning in the WIKI.

Thank you.
