### ISSUE TITLE
Maintain/Upcoming Downtime Message for all Users.

### ISSUE THREAD

**Issue by hansgru** [takezoe/gitbucket#623]
It would be really useful if it were possible to display a message to all logged in users, e.g. a "Maintain Message" or an "Upcoming Downtime Message" in order not to take the users by surprise.

**Comment by takezoe** [comment]
It will be possible by plug-in (like Greasemonkey script) in the future release. The first version of new plug-in system will be released in the next release 2.9.

In the current version of GitBucket, you can use administrator message for this purpose. This message is displayed at the sidebar of dashboard and the logged-in form.

**Comment by takezoe** [comment]
You might be possible to use [gitbucket-announce-plugin](https://github.com/McFoggy/gitbucket-announce-plugin) for your purpose.
