### ISSUE TITLE
Copy repositories/ directory to a different gitbucket installation?

### ISSUE THREAD

**Issue by curioustechizen** [takezoe/gitbucket#625]
Let me start off by mentioning this is not really an issue - it is more of a "I screwed up, please help me" question!

**Question: Is there a way to copy the `repositories/` directory of a gitbucket installation to a different installation provided the usernames are the same between the two?**

I have been running gitbucket internally for a small team of 3 people. I've using the `java -jar gitbucket.war` method - no servlet containers or stuff. 

Recently, the `data.h2.db` file got corrupted (don't ask me how - it is more embarrassing than you might imagine). So, I thought of simply installing gitbucket afresh, creating new users with the same usernames as before, and copying over the `repositores/` folder.

However, this does not work. I don't see the old repositories in gitbucket web UI.

If this approach does not work, is there any other way to migrate the repositories? Perhaps using some standard GIT procedure on the <repo-name>.git folders?

**Comment by takezoe** [comment]
GitBucket manages repositories by h2. So you can't move your repositories to new GitBucket instance only copying directory.

I think that the simplest solution is create an empty repository on new GitBucket instance and push your repository to there.

**Comment by curioustechizen** [comment]
@takezoe Yes - that'll work for repositories for which I have copies lying around, but some repos are pretty old and might only be present on the gitbucket server.

If I cd to any of the <repo-name>.git folders and spin up a temporary git server (I don't remember the command ... git-web ??) will I then be able to clone these repos?

**Comment by takezoe** [comment]
Repositries in the GITBUCKET_HOME/repositories directory are bare repository. You can clone working copy from them on the local file system.

**Comment by curioustechizen** [comment]
@takezoe Great. That'll do for me. Thanks!

**Comment by lavvy** [comment]
Please is there any reason why this beautiful application do not have the ability of migrating a repo from other git installations.?

**Comment by McFoggy** [comment]
> Please is there any reason why this beautiful application do not have the ability of migrating a repo from other git installation from web ui ?

Probably because no-one really had the need for and because no-one implemented it yet. 
If you have time you can perhaps help on such a feature.

Otherwise, you just have to go to the UI, create an empty repo, add this fresh new repo as a remote of the repo you want to migrate and make a git push to this new remote. 
Not that difficult at all. You can even script it if going to the UI is too long.

**Comment by lavvy** [comment]
Please i think it should have been among the first features. Not very much
people begin projects today from the scratch.
I would have tried my best to contribute a pull request but the biggest
problem i have is not being a java or scalar guy. I don't know why you
chose java or scala but you might have a genuine reason though.
Infact it was the main reason we use gogs but i believe in extensibility
and pluggable nature of gitbucket.

Please if that migration feature could be added it would be a big leap for
new comers.

**Comment by McFoggy** [comment]
@lavvy by doing the actions I have mentioned you will `import` your git history from your existing repository into gitbucket. That's just a plain git push from a repository with 2 remotes.

For example, supposing you are migrating your project (let's say https://github.com/lavvy/todo) from github to your own instance of gitbucket hosted on http://mygitbucket:8080, then you can:

- `$ git clone https://github.com/lavvy/todo.git`
- create an empty repo named `todo` on gitbucket for user lavvy
- `$ cd todo`
- `$ git remote add gitbucket http://mygitbucket:8080/git/lavvy/todo.git`
- `$ git push -u gitbucket master` 

_Et voilà,_ you're local git repository has 2 remotes, _origin_ pointing to github and _gitbucket_ pointing to your gitbucket. If now go to the gitbucket UI and hit refresh you will your full repository content.

If you are asking for a full feature import mechanism from other _'git hosting solutions'_ , like github, bitbucket, gitlab, ..., then please open another issue.

**Comment by lavvy** [comment]
Ok, i will open an issue,  i only requested to know if there is a standing
rule for not have implemented it. My bad.

I know how to push code to remote repo like you stated but many times we
code on the go only with the browser without downloading anything which is
the principal reason we use git web interfaces .
Anyways, thanks for the assistance.
