### ISSUE TITLE
Impossible to store config into MySQL DB

### ISSUE THREAD

**Issue by powertim** [takezoe/gitbucket#626]
Hi, I tried to use MySQL to store the config of GitBucket but I got this error message 

Class "com.mysql.jdbc.Driver" not found [90086-180]

Here is my configuration
![capture1](https://cloud.githubusercontent.com/assets/8004432/6128307/c610d0f0-b134-11e4-849a-3ebf3565882e.PNG)

Do you have any idea ?

Thanks for your help !
I love Gitbucket :+1:

**Comment by takezoe** [comment]
GitBucket supports only H2 currently. We have a plan to support other RDBMS but we can not declare when we will be possible to provide it.

**Comment by powertim** [comment]
Thanks a lot for your reply. That's not crucial for me to store settings in MySQL. I just wanted to be sure that I didn't mismatched my settings. So now, everything's clear 😊 .

**Comment by al34n1x** [comment]
Hi, I want to deploy GitBucket on a Docker container running Tomcat, but in order to keep data persistent I need to mount a volume from the host into docker, do you know if I can accomplish that with gitbucket? Can I access the data directory from outside the container? 
Thanks!

**Comment by McFoggy** [comment]
It should work. Just mount a persistent directory, and use it for your GITBUCKET_HOME.
[Directory.md](https://github.com/takezoe/gitbucket/blob/master/doc/directory.md) exposes the different possibilities to define the gitbucket working directory.

**Comment by al34n1x** [comment]
I've found this https://registry.hub.docker.com/u/f99aq8ove/gitbucket/ .. it's works without the App Server, I will run some changes on the Docker File to install Tomcat and I will expose the directory. Thanks!
