### ISSUE TITLE
Need some help to configure a WebHook for pulling to Web server

### ISSUE THREAD

**Issue by powertim** [takezoe/gitbucket#627]
Hi all,

Thanks to all for your great work on GitBucket !
I'm trying to create a WebHook to automate deployment from 'dev' branch to my web server in pre-production.

1st question : when I manually type 'git pull' on my web server, I need to authenticate, maybe a difficulty for the webhook ??!

2nd question : what kind of file do you expect for webhook ? Is PHP right ? (don't care ?) I found this post interesting : 
https://gist.github.com/marcelosomers/8305065
Could I start with this template ?

3nd question : how can adapt this code to let it work on Gitbucket ? Payload...

A full example or wiki would be very great and I'm sorry to ask all these questions, I'm beginner on Git and I try to do my best to understand almost concepts and how GitBucket works.
I just precise that I searched a lot into issues and on Google before posting this issue, so please be kind if I'm a truly noob for you :-)

Thanks to everyone who will help me !!

Tim.

**Comment by takezoe** [comment]
Close all questions. If you have any questions about GitBucket, please send them to [the gitter room](https://gitter.im/takezoe/gitbucket) instead of issue according to [the Guideline for Issues](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md).
