### ISSUE TITLE
Activity timeline hangs for users joining many groups

### ISSUE THREAD

**Issue by rela1470** [takezoe/gitbucket#638]
リポジトリの参照権限が多いユーザのみ、
ログイン後のマイページが表示できません。

多分ですが、アクティビティの数が多いと表示できなくなる印象です。
2.6 ~ 3.0で再現しています。

https://www.dropbox.com/s/xe9uxrz203k35ko/git.oratta.net.txt?dl=0
上記エラーが出るユーザーも、参加グループを減らすと表示できるようになります。
減らすグループはどのグループでも大丈夫なので、特定のデータが悪さしているようには見受けられませんでした。

**Comment by takezoe** [comment]
問題が出ているユーザのグループ数と、各グループのリポジトリ数の目安を教えていただけないでしょうか？

**Comment by rela1470** [comment]
一番少ない権限数だと、2リポジトリずつの6グループで再現しました。
エラーが起こる組み合わせを試していたところ、
サイズが大きなリポジトリへの参照権限があると、発生しやすいようです。

**Comment by takezoe** [comment]
ありがとうございます。参考になります。

**Comment by takezoe** [comment]
Merged to #441

**Comment by takezoe** [comment]
3.2で保存するアクティビティログの最大件数を指定できるようにしようと思います。
