### ISSUE TITLE
Anyone can create private repositories clone.

### ISSUE THREAD

**Issue by kazuwada** [takezoe/gitbucket#644]
Anyone can create private repositories clone on GitBucket 2.8 and 3.0.
GitBucket 2.7 works fine (Only collaborators)

**Comment by my-dev** [comment]
Hi Mr.atkezoe And Mr.kazuwada
i'm mamemo0823 ( my-dev )

about this issue.
In [ src/main/scala/gitbucket/core/servlet/BasicAuthenticationFilter.scala ] Line about 50

i guess change from
--------------------------------------
chain.doFilter(req, wrappedResponse)
---------------------------------------
to
---------------------------------------
if(getCollaborators(repository.owner, repository.name).contains(username)){
  chain.doFilter(req, wrappedResponse)
}else{
  requireAuth(response)
}
---------------------------------------

i checked it works.
maybe, it's ok.

How about this suggestion?

**Comment by my-dev** [comment]
oh!!! sorry...

this code is insufficiency...

by this code, my push action is denied too.
Hmm.....

i think more.

**Comment by takezoe** [comment]
@my-dev Thanks for your suggestion. However I fixed this issue by other way because your proposed code still contains some problem. I think my fix covers all cases which require authentication.

**Comment by my-dev** [comment]
Hi! Mr.takezoe
sure.

i'm looking forward to see it.
i'll learn more.

thank you.
