### ISSUE TITLE
About [ Disable Check Box ] In User Management Page

### ISSUE THREAD

**Issue by my-dev** [takezoe/gitbucket#645]
grad to see you.
from mamemo0823 to you

[ Administration ] -> [ UserManagement ] -> [ Someone Profile Edit ]
In this page, Normally do update user information under [ Disable Check Box ] is OFF.
But system receives as it's ON.
Then i can't update the information.

Maybe, Line 198 about in UserManagementController.scala,

Please check this issue.

**Comment by takezoe** [comment]
Hmm... Do you mean that disabled users are removed from the user list?
You can see disabled users by checking [Include removed users] checkbox at above of the user list.

**Comment by my-dev** [comment]
Hi. Mr.takezoe
thanks your comment.

The next page you say, click on Edit button to _edituser's page.
in source, UserManagementController.scala
I think that the function [ disableByNotYourself ] relates with this issue.

sorry my poor English.

**Comment by takezoe** [comment]
Other user disabled your user?
Disable means remove user logically in GitBucket. Therefore, disabled users can not change their information usually. and also GitBucket does not allow to disable your account by yourself in administration page.
I can't understand your situation clearly...

**Comment by my-dev** [comment]
sorry!
i talk about just in [ _edituser page ]...

please see below.

src/main/scala/gitbucket/core/controller/UserManagementController.scala の190行目付近

I guess change from
------------------------------------------------------------------------------------------
protected def disableByNotYourself(paramName: String): Constraint = new Constraint() {
  override def validate(name: String, value: String, messages: Messages): Option[String] = {
    params.get(paramName).flatMap { userName =>
      if(userName == context.loginAccount.get.userName){
        Some("You can't disable your account yourself")
      }else{
        None
      }
    }
}
------------------------------------------------------------------------------------------
to->
------------------------------------------------------------------------------------------
protected def disableByNotYourself(paramName: String): Constraint = new Constraint() {
  override def validate(name: String, value: String, messages: Messages): Option[String] = {
    params.get(paramName).flatMap { userName =>
      if(userName == context.loginAccount.get.userName){
         params.get("removed").flatMap { removed =>
           if(removed == "true"){
             Some("You can't disable your account yourself")
           }else{
             None
           }
         }
      }else{
        None
      }
    }
  }
}
------------------------------------------------------------------------------------------
How about this logic...

**Comment by takezoe** [comment]
Oh, I see. You are right. I will fix as you say. Thanks for your feedback!

**Comment by my-dev** [comment]
It's my pleasure.
