### ISSUE TITLE
i suggest that you add [ autocomplete="off" ] in [ core/account/edit.scala.html ]

### ISSUE THREAD

**Issue by my-dev** [takezoe/gitbucket#646]
Hi! Mr.takezoe

i suggest that you add [ autocomplete="off" ] in [ core/account/edit.scala.html ]'s password section.

such like
\---------------------
\<input type="password" name="password" id="password" value="" />
->
\<input type="password" name="password" id="password" value="" autocomplete="off" />
\---------------------

it's not big problem, but for better usability.

thank you.

**Comment by takezoe** [comment]
@my-dev Thanks. You can send such improvements as pull request :-)
