### ISSUE TITLE
GistプラグインのSnipetリンクでコンテキストパスが省略されてしまう

### ISSUE THREAD

**Issue by nantan** [takezoe/gitbucket#647]
GitBucket3.0へのバージョンアップに合わせて、新しいgistプラグインも導入してみました。
その際に、以前のプラグインシステムでも発生していたのですが、「Snipet」リンクがコンテキストパスが省略されたURLになってしまいます。

（正しいURL）`https://hogeserver/gitbucket/gist`
（リンクURL）`https://hogeserver/gist`

System SettingsのBase URLは `https://hogeserver/gitbucket` に設定してあります。

**Comment by takezoe** [comment]
This problem has been already reported in gitbcuket-gist-plugin repository:
https://github.com/takezoe/gitbucket-gist-plugin/pull/1

Thanks for your reporting.
