### ISSUE TITLE
Last One Administrator can change [ User Type ] to [ Normal ]

### ISSUE THREAD

**Issue by my-dev** [takezoe/gitbucket#650]
Hi! Mr.takezoe.
this is mamemo0823 ( my-dev ).

again, In [_edituser Page].
At [ User Type: ] section.

Last One Administrator can change [ User Type ] to [ Normal ]...
I think, Maybe It's not good.

Then i suggest these codes

\-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
### [ src/main/twirl/gitbucket/core/admin/users/user.scala.html ]

1st, In [ User Type ] Section...
\-------------------------------------------------------
\<fieldset>
  \<label class="strong">User Type:</label>
  \<label class="radio" for="userType_Normal">
    \<input type="radio" name="isAdmin" id="userType_Normal" value="false"@if(account.isEmpty || !account.get.isAdmin){ checked}/> Normal
  \</label>
  \<label class="radio" for="userType_Admin">
    \<input type="radio" name="isAdmin" id="userType_Admin" value="true"@if(account.isDefined && account.get.isAdmin){ checked}/> Administrator
  \</label>
\</fieldset>
\-------------------------------------------------------
\-> 
\-------------------------------------------------------
\<fieldset>
  \<label class="strong">User Type:</label>  
#####  \</div>  
  \<label class="radio" for="userType_Normal">
    \<input type="radio" name="isAdmin" id="userType_Normal" value="false"@if(account.isEmpty || !account.get.isAdmin){ checked}/> Normal
  \</label>
  \<label class="radio" for="userType_Admin">
    \<input type="radio" name="isAdmin" id="userType_Admin" value="true"@if(account.isDefined && account.get.isAdmin){ checked}/> Administrator
  \</label>
\</fieldset>
\-------------------------------------------------------

### [ src/main/scala/gitbucket/core/service/AccountService.scala ]
2nd, define a function such like this...
\-------------------------------------------------------
def getAdminUsers(includeRemoved: Boolean = true)(implicit s: Session): List[Account] = {
  if(includeRemoved){
    Accounts filter (_.isAdmin === true.bind) sortBy(_.userName) list
  } else {
    Accounts filter (t=>(t.removed === false.bind) && (t.isAdmin === true.bind)) sortBy(_.userName) list
  }
}
\-------------------------------------------------------

### [ src/main/scala/gitbucket/core/controller/UserManagementController.scala ]
3rd, modify such like this
\-------------------------------------------------------
  val editUserForm = mapping(
.....
#####    "isAdmin"     -> trim(label("User Type"    ,boolean(checkLastAdminUser()))),
.....
  )(EditUserForm.apply)
\-------------------------------------------------------

and add function such like this...

\-------------------------------------------------------
  protected def checkLastAdminUser (): Constraint = new Constraint() {
    override def validate(name: String, value: String, messages: Messages): Option[String] = {
      params.get("isAdmin").flatMap { isAdmin =>
        if(isAdmin == "false"){
          if(getAdminUsers(false).length == 1){
            Some("Deny! Because This user is Last Administrator...")
          }else{
            None
          }
        }else{
          None
        }
      }
    }
  }
\-------------------------------------------------------
\-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

How about this suggestion?

**Comment by takezoe** [comment]
Thanks for your proposal. This issue has been closed because duplicated but referenced from #533.

**Comment by my-dev** [comment]
Oh! Sorry...Mr.takezoe.
i'm sure.

**Comment by takezoe** [comment]
No problem. Your proposed code will help us :+1:
