### ISSUE TITLE
Other User can disable [ !!!Last!!! ]  Administrator.

### ISSUE THREAD

**Issue by my-dev** [takezoe/gitbucket#651]
Hi! Mr.takezoe.
this is mamemo0823 ( my-dev ).

again, In [_edituser Page].
At [ Disabled: ] section.

Maybe this situation is difficult to find...

#### (4) Edit [ xxx ]'s Disable Flag from [ Off ] to [ On ]

As you are about to see, This system has no Administrator...

Maybe, [ Now gitbucket's version ] contains this problem.

Then i suggest these codes

\-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
\-------------------------------------------------------
#### [ src/main/scala/gitbucket/core/service/AccountService.scala ]
define a function
\-------------------------------------------------------
def isAdmin(userName: String)(implicit s: Session): Option[Account] =
  Accounts filter(t => (t.userName === userName.bind) && (t.isAdmin === true.bind)) firstOption
\-------------------------------------------------------
#### [ src/main/scala/gitbucket/core/controller/UserManagementController.scala ]
modify such like this
\-------------------------------------------------------
protected def disableByNotYourself(paramName: String): Constraint = new Constraint() {
  override def validate(name: String, value: String, messages: Messages): Option[String] = {
    params.get(paramName).flatMap { userName =>
      if(params.get("removed") == Some("true")){
        if(userName == context.loginAccount.get.userName){
          Some("You can't disable your account yourself")
        }else{
          // [ loginUser ] is not equal [ targetUser ]
          if(isAdmin(userName) != "None" && getAdminUsers(false).length == 1) {
            Some("Deny! Because This user is Last Administrator...")
          }else{
            None
          }
        }
      }else{
        None
      }
    }
  }
}
\-------------------------------------------------------
/-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

How about this suggestion?

**Comment by takezoe** [comment]
See #533

**Comment by takezoe** [comment]
Thanks for your proposal. This issue has been closed because duplicated but referenced from #533.

**Comment by my-dev** [comment]
sorry.
i'm sure.

**Comment by takezoe** [comment]
No problem. Your proposed code will help us :+1:
