### ISSUE TITLE
Spacing under branch view in Firefox

### ISSUE THREAD

**Issue by ziggystar** [takezoe/gitbucket#654]
There is some space missing between lines in the branch view. The spacing looks much better when I disable the `line-height: 100%` directive, which I highlighted on the left.

![gitbucket spacing](https://cloud.githubusercontent.com/assets/459632/6638535/63481a12-c987-11e4-8270-a4ad86676339.png)

**Comment by takezoe** [comment]
I tested Firefox 36.0.1 on Mac. But I couldn't see the collapsed branch view. Could you give us more information about your environment?
![branch](https://cloud.githubusercontent.com/assets/1094760/6650227/4a4ba7a4-ca4a-11e4-9733-3f4f3b28ac27.png)

**Comment by ziggystar** [comment]
I cannot reproduce the behavior anymore. The `default` marker is now on the same line as in your screenshot.

I'm currently at 36.0.1, too.

**Comment by takezoe** [comment]
I expect that had been caused by CSS cache.
