### ISSUE TITLE
upgrade error from 2.7 to 3.0 or 2.8

### ISSUE THREAD

**Issue by kimitake** [takezoe/gitbucket#659]
I have 2.7 project site and replaced gitbucket.war of 3.0 or 2.8, and then access the site, so I got the following error.

org.h2.jdbc.JdbcSQLException: Table "ACTIVITY" not found; SQL statement:
select x2.x3, x2.x4, x2.x5, x2.x6, x2.x7, x2.x8, x2.x9, x2.x10 from (select x11.x12 as x9, x11.x13 as x6, x11.x14 as x5, x11.x15 as x4, x11.x16 as x8, x11.x17 as x10, x11.x18 as x3, x11.x19 as x7 from (select x20."ACTIVITY_DATE" as x12, x20."ACTIVITY_TYPE" as x13, x20."ACTIVITY_USER_NAME" as x14, x20."REPOSITORY_NAME" as x15, x20."ADDITIONAL_INFO" as x16, x20."ACTIVITY_ID" as x17, x20."USER_NAME" as x18, x20."MESSAGE" as x19 from "ACTIVITY" x20) x11 inner join (select x21."UPDATED_DATE" as x22, x21."PARENT_REPOSITORY_NAME" as x23, x21."DEFAULT_BRANCH" as x24, x21."DESCRIPTION" as x25, x21."ORIGIN_REPOSITORY_NAME" as x26, x21."ORIGIN_USER_NAME" as x27, x21."PARENT_USER_NAME" as x28, x21."PRIVATE" as x29, x21."REPOSITORY_NAME" as x30, x21."USER_NAME" as x31, x21."REGISTERED_DATE" as x32, x21."LAST_ACTIVITY_DATE" as x33 from "REPOSITORY" x21) x34 on (x11.x18 = x34.x31) and (x11.x15 = x34.x30) where x34.x29 = ? order by x11.x17 desc limit 30) x2 [42102-180]

If I setup a site from scratch using 2.8 or 3.0, there is no issue.

**Comment by takezoe** [comment]
I think that your GitBucket failed to automatic migration by abnormal reason like accessing during migration. In such a case, you have to replay diffs between the succeeded point and the failed point manually for the broken instance.

Could you show your table list of H2 and the content of `GITBUCKET_HOME/version`?

**Comment by kimitake** [comment]
1. How can I get table list of H2?

2. Currently the version is 2.7 (Now I'm using 2.7 package)
After I upgraded to 3.0, the version file was changed to 3.0, but the GitBucket site showed 0.0.
Then I replaced to 2.8, at that time I didn't check the version file, but the GitBucket still showed 0.0.
Even I replaced to 2.7, the version file was 3.0, so I modified it to 2.7 manually.

BTW, I'm not sure but I have installed 2.3 at first, and then upgraded to 2.7 (or 2.6).

**Comment by takezoe** [comment]
You can use H2 web console from the system administration console of GitBucket. Fill sign-in form like below and click `Connect` button, then you can access H2.
![2015-04-08 2 28 01](https://cloud.githubusercontent.com/assets/1094760/7029211/f09ac20c-dd96-11e4-8c3a-5d741ba36727.png)

**Comment by kimitake** [comment]
![h2table](https://cloud.githubusercontent.com/assets/84445/7030736/6e215366-dd1b-11e4-9431-5db575970fe0.png)

**Comment by takezoe** [comment]
INFORMATION_SCHEMA is system tables of H2. What's top level tables? Correct table list is here:
![2015-04-08 7 52 04](https://cloud.githubusercontent.com/assets/1094760/7035508/39bd7bc8-ddc4-11e4-92ed-d994c04da26e.png)

**Comment by kimitake** [comment]
There are no tables at top level. What is JDBC URL?

**Comment by takezoe** [comment]
See the first screenshot.

**Comment by kimitake** [comment]
Even if I specify ~/.gitbucket/data, there is no table.

**Comment by takezoe** [comment]
Hmm... H2 data is broken? But I've never seen such broken state.
At first, If H2 data is broken, you can't sign-in to GitBucket. So I think H2 data is living.
Do you set GITBUCKET_HOME?

**Comment by kimitake** [comment]
I'm running Gitbucket on Windows at D:\GitBucket folder.
The following is the batch file to start gitbucket process.
  java -jar D:\GitBucket\gitbucket.war --port=9080 --gitbucket.home=D:\GitBucket\

I found C:\users\kimitake\.gitbucket\data.mv.db, so just renamed it, then the file was created automatically when I clicked "Test connection" button on H2 console.

There is same file at D:\GitBucket folder, so just copied it to ~/.gitbucket/ and clicked "Test connection" button (username is sa, password is blank), but in this case, the console shows "Wrong username or password" error.

Does 2.7's data.mv.db use different username/password?
I guess 2.8 or 3.0 migration process cannot access the file (D:\GitBucket's one) and failed to upgrade.

**Comment by kimitake** [comment]
Is it possible to migrate the repository manually?
I'm thinking to prepare new Gitbucket and I will be able to push all repository to new one, but how can I export user info?

**Comment by fujisaks** [comment]
If you are still trying to use H2 Console, what about ./data, which is a relative path from your gitbucket.war?
Or maybe another relative path from java.exe's current working directory?
If you get  "Wrong username or password" error then, your src/main/resources/database.conf will help you.

**Comment by takezoe** [comment]
Close all questions. If you have any questions about GitBucket, please send them to [the gitter room](https://gitter.im/takezoe/gitbucket) instead of issue according to [the Guideline for Issues](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md).
