### ISSUE TITLE
Change GITBUCKET_HOME to Network drive

### ISSUE THREAD

**Issue by FlYnN91** [takezoe/gitbucket#661]
Hi, I am trying to utilse GitBucket on windows with IIS and Jetty. everything works great. I would like to change the GITBUCKET_HOME directory so that all repositories are stored on a network drive. I tried changing the GITBUCKET_HOME to a mounted drive letter, but when restarted I get Service Unavailable.
I have also tried creating folder links. Assigning various premissions. I also tried using full UNC path.

Any help/advice would be appreciated.

**Comment by damnhandy** [comment]
This works in Linux and Mac OS X environments. I am running Gitbucket on EC2 and have set my `GIT_BUCKET` home to a mounted EBS volume and everything works without a hitch. I wonder if this is is Windows-specific error? Do you have any output you could share?

**Comment by FlYnN91** [comment]
I really wish I could find any logs but I cannot find location where any logs are being created In Windows.

**Comment by marklacroix** [comment]
I was able to get Gitbucket to start on Windows using a network share as the GITBUCKET_HOME. In my case, it took 2h35m for Jetty to extract the war file over the network (VPN over the internet, double whammy) plus several more minutes just to initialize. Try running Gitbucket outside of IIS to see if any errors are thrown or if it's just a long delay from extracting files. I used `java -jar gitbucket.war --gitbucket.home=\\hostname\sharename\gitbucket` from a cmd prompt. All of the messages appear as standard output.

**Comment by takezoe** [comment]
It might be better to be able to be specify the war extraction directory as different location from GITBUCKET_HOME to reduce initialization time.

But even so, I don't recommend using network drive as GITBUCKET_HOME because GitBucket accesses to Git repositories frequently.

**Comment by FlYnN91** [comment]
Thanks for the suggestion guys. I think, I have discovered a solution. I've decided to use some software the syncs the gitucket_data to a network drive in realtime. As well as that, do a nightly backup off the gitbucket_data folder.

Thanks

**Comment by SaimonL** [comment]
Setting Git Bucket home does not work and freezes.
This happens on NFS mount where NFS is mounting EXT4 file system and I can write on it and everything.
Using Ubuntu 14.04 (64-Bit)

```bash
echo $GITBUCKET_HOME
/home/vagrant/git

ls -l
total 53732
-rw-rw-r-- 1 vagrant vagrant 55015539 Jun 26 21:22 gitbucket.war
drwxr-xr-x 3 vagrant vagrant     4096 Jul  4 08:09 tmp/

df -h /home/vagrant/git
Filesystem                       Size  Used Avail Use% Mounted on
192.168.121.1:/mnt/SERVICES/Git  2.7T  135M  2.6T   1% /home/vagrant/git

java -jar gitbucket.war
2015-07-04 08:09:23.457:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2015-07-04 08:09:23.535:INFO:oejw.WebInfConfiguration:Extract jar:file:/home/vagrant/git/gitbucket.war!/ to /home/vagrant/git/tmp/webapp
```

Ans it freezes and nothing happens here.

**Comment by marklacroix** [comment]
This is typical behavior. It's not actually frozen here, just taking a long time to perform the war extraction since it's happening over a network share. You can monitor the progress in /home/vagrant/git/tmp/webapp from another shell. My version 3.3 instance currently uses 86M in the tmp/webapp dir

**Comment by SaimonL** [comment]
Yes you are correct. After 10 minutes I see it working now.
Thanks

**Comment by RobertoFlores** [comment]
is there a way to run the gitbucket.war file in windows service style?

**Comment by McFoggy** [comment]
@RobertoFlores it is currently the way I run gitbucket. For windows services now I am using [NSSM](https://nssm.cc/usage).

**Comment by RobertoFlores** [comment]
Thanks a lot McFoggy :+1:

**Comment by SaimonL** [comment]
If you use Vagrant with VirtualBox and use "synced_folder" to sync local host to guest vm and use type 'NFS' loop back then it takes 10 minutes to work. 
However if you use the default type which is VirtualBox local loop back then it takes less them 1 minute. They both are external connection however NFS is not fully understood by Java.
