### ISSUE TITLE
New pull requests should default to upstream master

### ISSUE THREAD

**Issue by calid** [takezoe/gitbucket#668]
The addition of #611 is awesome.  However if it would be nice if upon creating a new pull request it defaulted to the upstream master instead of the current repo master.

Compare:

![selection_028](https://cloud.githubusercontent.com/assets/494405/6790539/6212adb4-d176-11e4-8833-ad4ae82708d2.png)

With the Github equivalent:

![selection_029](https://cloud.githubusercontent.com/assets/494405/6790617/ed25d2dc-d176-11e4-8060-98446f22ad6c.png)

Thanks!

**Comment by takezoe** [comment]
Fixed in #810
