### ISSUE TITLE
regression: blank diff output

### ISSUE THREAD

**Issue by calid** [takezoe/gitbucket#672]
Using the development trunk I'm having rendering issues with commit diffs.  `git bisect` indicates the bug was introduced in aa35498.

This is what diff output looks like at 14becd0 (one commit before):

![selection_031](https://cloud.githubusercontent.com/assets/494405/6802308/4a855124-d1fd-11e4-8ee1-b86cc64234eb.png)

And this is what the output looks like at aa35498 (as well as current HEAD 1341ef9):

![selection_030](https://cloud.githubusercontent.com/assets/494405/6802328/7910d7d4-d1fd-11e4-9264-2a4479ce50c8.png)

I'm getting this issue on both Linux and Windows, as well as Internet Explorer 9 and Firefox v31-36

**Comment by takezoe** [comment]
Fixed in #672
