### ISSUE TITLE
Fork button does not work on some browsers

### ISSUE THREAD

**Issue by calid** [takezoe/gitbucket#677]
Clicking the Fork button has no effect on these browsers:
* Firefox v31.5.0 (Centos6)
* Firefox v36.0.4 (Windows 7)
* Internet Explorer 9

For firefox the fork button _does_ work if the user belongs to a group.

For internet explorer the fork button doesn't work in either case.  It always takes me to a page that asks "Where should we fork this repository?", but clicking the displayed user/group avatars has no effect.

**Comment by mittorn** [comment]
Why it is closed? Still does not work for me!
