### ISSUE TITLE
jquery-hashchange-plugin is not supported jquery 1.9

### ISSUE THREAD

**Issue by nazoking** [takezoe/gitbucket#679]
jquery.ba-hashchange.js use `$.browser`
https://github.com/takezoe/gitbucket/blob/73766f11ebdfd99d4c2742c4a4681b3c42783c3a/src/main/webapp/assets/vendors/jquery/jquery.ba-hashchange.js#L300

but jquery removed `browser` property since version1.9.0.
http://api.jquery.com/jquery.browser/
(gitbucket used version is 1.9.1)

IE console report those error.
```
SCRIPT5007: 未定義または NULL 参照のプロパティ 'msie' は取得できません
ファイル: jquery.ba-hashchange.js、行: 273、列: 5
```

**Comment by takezoe** [comment]
Fixed in #680
