### ISSUE TITLE
Please remember, about [ closed issue #650 and #651] again...

### ISSUE THREAD

**Issue by my-dev** [takezoe/gitbucket#682]
Hi! Mr.takezoe.

this is mamemo0823 ( my-dev )

It's pleasure, Gitbucket V3.1 is released.
I've been waiting for.

I tried to check, closed issues [ #644, #646, #650, #651 ]

I think, #644 And #646 works nice!!! thanks.

but #650, #651 is not works.
Please again, remember #650 & #651...

Now I'm build [ fixed this Version ] by myself...
I think, my suggest source is work good.
And It solves Just #533.

#650, #651 means that there are none administrator in this system.
In fact, no one can do [ Administrate Operating ]...

I think, It's bad condition...

If possible, Please handle #650 & #651 again.

thank you.

**Comment by takezoe** [comment]
#650 and #651 was merged to #533. #533 is still opening.

**Comment by my-dev** [comment]
Hi! Mr.takezoe.
Sorry And Thank you.
