### ISSUE TITLE
In V3.1 & 3.1.1, Not work the WebHook By https [ with self-signed certification ]...

### ISSUE THREAD

**Issue by my-dev** [takezoe/gitbucket#683]
Hi! Mr.takezoe.

the webhook by https is not work in V3.1
by http, It works nice!

In V3.0, It works nice!

I think, It's important function.

**Comment by hantsy** [comment]
In my experience, V3.1 WebHook did not work at all, either https or http.

After I downgraded it from V3.1 to V3.0,  the WebHook worked.

I was using Jenkins 1.606, GitBucket Plugin 0.5.1. The Webhook only worked well with GitBucket V3.0 or lower version.

**Comment by my-dev** [comment]
Hi! Mr.hantsy.

Now I checked again [ Webhook ] By HTTP at V3.1.
In my case, It works good...

[ by HTTPS ] didn't work.

At V3.0, you say, both of them work good!!!

my report...

**Comment by hantsy** [comment]
@my-dev  I installed the dev tools(Redmine, Nexus, GitBucket, Jenkins) in a fresh linux yesterday and encountered the problems.

When I replaced GitBucket  V3.1 with an old version V3.0, it worked, no config changed in Jenkins.

**Comment by ssogabe** [comment]
@hantsy 
GitBucket plugin v0.7 has just been released. it supports GitBucket v3.1. try it.
https://wiki.jenkins-ci.org/display/JENKINS/GitBucket+Plugin

**Comment by hantsy** [comment]
@ssogabe  Verified!  Worked again with GitBucket V3.1 after I upgraded the Jenkins GitBucket Plugin to V0.7!!!

Many thanks.

**Comment by my-dev** [comment]
Mr.hantsy & Mr.ssogabe 's problem may be solved. but this issue is not soloved.

Mr.takezoe, I'm waiting for your handling. please.

**Comment by ssogabe** [comment]
@my-dev Are you using a self-signed SSL Certificate on Jenkins? If so, check your gitbucket log.
If you can find the following exception, [1] will help you. 

"javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: "

[1] http://wsigrid.blogspot.jp/2008/12/how-to-solve-javaxnetsslsslhandshakeexc.html

**Comment by my-dev** [comment]
Mr.ssogabe.
thanks your comment.

Now, JENKINS doesn't relate. Please forget JENKINS...

Yes, I see.
I use self-signed SSL Cert...And I regist it to JRE's cacerts...
It's I see. such like quite basic thing...

what I say is that it works until V3.0, but Not work In V3.1...
so, I write this issue.

Once, Please try yourself...
If you success In your environment, Please tell me...

**Comment by ssogabe** [comment]
For what it's worth, the payload posted from WebHook is different from the old ones.
see https://github.com/jenkinsci/gitbucket-plugin/pull/11

**Comment by my-dev** [comment]
In Japanese sorry...

ソガベさん、いろいろとご指摘ありがとうございます。
caceartsへのprivate キーの登録などは至極当然として処理しおります。
初歩的なミスは一切ご考慮いただく必要はございません。
まずこの点、ご心配には及びません。

JENKINSも一切関係ございません。
hantsyさんが話題に出されただけでして、この報告(issue)はそもそもJENKINSとは一切無関係でございます。

V3.0までは、httpsでのWebhookが正常に動作しており、
V3.1になって初めて、httpsでのWebhookができなくなったとお伝えしている次第です。

payloadの内容が古い物と違う・・・云々も関係ございませんでして、

現状、私のWebhookされる側では、ログファイルを吐き出して、exitしているだけの処理としておます。
それでも、httpでのWebhookは正常に動作するものの、httpsになると失敗してしまうというわけです。
つまり、叩かれたらファイルを吐き出してexitしているだけなので、payloadは無関係ということをご了承下さい。

宜しければ、
src/main/scala/gitbucket/core/service/WebHookService.scala
をご覧下さいませ。

f.onSuccess と f.onFailure のブロックがあります。
httpでのWebhookの場合は、onSuccessブロックに入るが、
httpsだと、onFailureに入ります。

V3.0とV3.1、V3.1.1 で、このソースファイルが大幅に改修されたようです。
が、Futureブロックに関して言えば、
httpPost.addHeader("X-Github-Event", eventName)
が追記されたのみようです。
その他には特に変更がなされた様子はありません。

少々細かい説明になりましたが、オレオレ証明書であれ、正規の証明書であれ、
httpsでのWebhook処理ができなくて困ってるぞ～。というのが、このissueの内容です。

もう一度言いますが、JENKINSやそのプラグイン云々ではないのです。
もちろん、REDMINEなども切り離して下さいませ。

上記を踏まえ、ご自身でも試していただければ、私が言っている事がすぐにご理解いただけると思います。
httpならOK
httpsでNG
ホント、すぐ判りますから。。。
試してみてから今一度書き込み等をお願い致します。

日本語で失礼しました。
英語だと、細かい表現が難しかったので・・・・・以後、極力英語で書きますので、ご理解下さい。

失礼しました。

**Comment by ssogabe** [comment]
v3.0ではわかりませんが、v3.1ではhttpsで動いていますよ。

**Comment by my-dev** [comment]
そうですか。
では私の方も今一度調べてみますが、、、重要なのは、オレオレ証明書ですが、その点いかがでしょうか？
正規の証明書だと、よく見るあの「確認フェーズ」が発生しないので、通過して当然でございます。

**Comment by ssogabe** [comment]
オレオレ証明書ですよ。
onFailureにいってれば、ログに”Failed: web hook request to ${webHookUrl.url}" のあとに何か原因がつかめるようなメッセージが出そうですが。
あとはアクセスログとか。

**Comment by my-dev** [comment]
なんと・・・とほほほ。(悲)
TOMCATや、JREのバージョンをお教えいただけませんでしょうか？

お手数お掛け致しますが、宜しくお願いします。

**Comment by ssogabe** [comment]
OpenJDK 1.7.0_75
Jetty 9.1.0.v20131115
nginx 1.7.11
で、nginxでssl設定しています。

**Comment by my-dev** [comment]
私は、
JDK 1.8.0_40
tomcat 8.0.20
apache 2.2.27

で、apacheにてssl設定しております。

ちなみに、今、同じ状態のまま、「V3.0」「V3.1」「V3.1.1」にて動作検証しました。

【V3.0】
httpとhttps　OK

【V3.1】
http　OK
https　NG

【V3.1.1】
http　OK
https　NG

でした。

**Comment by ssogabe** [comment]
apacheとtomcatのアクセスログなどをチェックして、どこまでリクエストが来ているのか、レスポンスコードは何なのかとか、切り分けてみたらどうでしょうか。

**Comment by my-dev** [comment]
・・・すみませんが、そこまで時間を割いてるわけにも行かず・・・T_T
ただただ、私のお伝えした環境ではhttpsでのWebhookができないよ。という報告です。
ssogabeさんの環境では成功してるのですよね？それはそれで良しとしましょう。
ですが、私の環境では動作していたものが動作しなくなったので、報告している次第です。

【以下、ログですが、何か参考になれば・・・】
09-Apr-2015 10:55:15.499 INFO [ajp-nio-8009-exec-1] com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$InfoLogger.log Initializing c3p0-0.9.5 [built 02-January-2015 13:25:04 -0500; debug? true; trace: 10]
09-Apr-2015 10:55:16.010 INFO [ajp-nio-8009-exec-1] com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$InfoLogger.log Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> z8kflt981794iv91h9kw4b|1282bbb, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.h2.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceUseNamedDriverClass -> false, identityToken -> z8kflt981794iv91h9kw4b|1282bbb, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, jdbcUrl -> jdbc:h2:/path/to/tomcatProjectHome/gitbucketHOME/data;MVCC=true, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
09-Apr-2015 10:56:19.952 SEVERE [ForkJoinPool-1-worker-1] gitbucket.core.service.WebHookService$$anonfun$callWebHook$1$$anonfun$apply$2.applyOrElse Failed: web hook request to https://path/to/yourhook.zzz
 javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
	at sun.security.ssl.ClientHandshaker.handshakeAlert(ClientHandshaker.java:1410)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2004)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1113)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:290)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:259)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:125)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at gitbucket.core.service.WebHookService$$anonfun$callWebHook$1$$anonfun$1.apply$mcV$sp(WebHookService.scala:58)
	at gitbucket.core.service.WebHookService$$anonfun$callWebHook$1$$anonfun$1.apply(WebHookService.scala:49)
	at gitbucket.core.service.WebHookService$$anonfun$callWebHook$1$$anonfun$1.apply(WebHookService.scala:49)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by my-dev** [comment]
ありがとうございます。
もしかすると、単なる私のミスかもしれません。
ログをよ～く見てみたところ、hand shakeの付近で「unrecognize name」が出ていたので、もしかするとServer Nameと不一致が原因？と思い、修正したところ、それが出なくなりました。。。

で、今は、
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
の部分を潰してみてるところです。
が、それにしても、3.0から3.1へバージョンアップした途端にこの現象が起こるのは・・・・・

**Comment by my-dev** [comment]
みなさん、大変お騒がせ致しました。
本件は、バグではなく、私の勉強不足によるものだったようです。
それにしても、落とし穴に落とされた気分ですが・・・T_T ボソッ。

無事、解決致しました。
本当に申し訳なく思います。

結果から言うと、JNIのPath構成の際のverifyがオレオレ証明書に対しても相当厳しくなった事が原因のようでした。
証明書作成の際のCommonNameと、ServerName(apacheの場合)が一致している必要あるようです。
この点に私は気付かず、突然動作しなくなった事を理由にバグと報告してしまいました。

本当にすみませんでした。
takezoe様、ご確認いただけましたら、本件はクローズで良いと思われます。

宜しくお願い致します。

それにしても、突然こんな厳しさが導入されるとは・・・ぐすん。T_T
