### ISSUE TITLE
Upgrade from 3.0 to 3.1 fails

### ISSUE THREAD

**Issue by violentinternet** [takezoe/gitbucket#692]
Upgrading from 3.0 to 3.1 results in application server/container just hanging on startup. I stopped the server after approximately 30min. My setup is a powerful GNU/Linux box with Tomcat7 and OpenJDK7-JRE. I tried to redeploy the app restarting tomcat. 
All previous upgrades from ~2.2 till 3.0 worked flawlessly within the same setup. Unfortunately nothing is in the logs except "[...] deploying gitbucket.war [...]". Going back to 3.0 again works fine.

Had somebody with similar setup managed to upgrade or having same issues?

Thx in Advance.

**Comment by takezoe** [comment]
It might be H2 version compartibility issue. Some users are saying it worked by replacing h2-1.4.186.jar with h2-1.4.180.jar in gitbucket.war.

We will release 3.1.1 with h2-1.4.180 to avoid H2 version compatibility issue as soon as possible.

**Comment by violentinternet** [comment]
That was it. Thx.
