### ISSUE TITLE
web ui merge does not update pull request that already exist

### ISSUE THREAD

**Issue by troter** [takezoe/gitbucket#700]
Steps to Reproduce.

1. create pull request A (from develop into master)
2. create pull request B (from feature into develop)
3. merge pull request B via web ui (update develop branch)
4. pull request A should be updated, but actual it is not updated.

PullRequestsControllerBase "/:owner/:repository/pull/:id/merge" should call PullRequestService.updatePullRequests.

**Comment by harupong** [comment]
+1 for this, and here is the case. While the pull request gets marked as "merged" when I do the following with GitHub as remote, when I do the same with GitBucket as remote, the pull request stays open, which is quite odd. 

1. create pull request X (from topic into master)
1. merge topic into master locally
1. push master to remote

Furthermore, if you click "Merge Pull Request" button on GitBucket after following the steps above, it still creates the merge commit which introduces no change at all(of course, the change has been merged already). That seems odd as well.

**Comment by takezoe** [comment]
Fixed in #921
