### ISSUE TITLE
Markdown list generation bug

### ISSUE THREAD

**Issue by FlYnN91** [takezoe/gitbucket#704]
Hi all,

I've been really impressed with this project. Just wanted to inform you about a bug I seem to have discovered.
I made a very simple list (GitHub documentation): (formatting is messed up)
<div>
1. Item 1
2. Item 2
3. Item 3
   * Item 3a
   * Item 3b
4. Item 4
5. Item 5
6. Item 6
</div>
GitBucket does not seem to process the list after the sub points correctly. It marks items 4,5,6 as 1,2,3
making it looks like two separate lists.

Thanks

**Comment by uli-heller** [comment]
```
1. Item 1
2. Item 2
3. Item 3
    * Item 3b
4. Item 4
5. Item 5
6. Item 6
```

... looks OK on Github and on Gitbucket:

![image](https://cloud.githubusercontent.com/assets/1677414/7105440/05f87902-e119-11e4-8200-40a3084d6f7d.png)

I don't see any bug.

**Comment by FlYnN91** [comment]
Gitbucket 3.0 running on Windows 7 IIS
New Issue (write):
![gibucket-write](https://cloud.githubusercontent.com/assets/774118/7115125/e93181e6-e1dc-11e4-8901-533f00380347.PNG)
preview:
![gibucket-preview](https://cloud.githubusercontent.com/assets/774118/7115127/ef3c4e4a-e1dc-11e4-9ffd-8714939d7e5a.PNG)

**Comment by FlYnN91** [comment]
Oh ok. I see. You have to have 4 spaces on the sub item before it becomes visible.
