### ISSUE TITLE
URL with / at the end returns 404 error

### ISSUE THREAD

**Issue by sylph01** [takezoe/gitbucket#711]
When I tried to access a repository with an URL that has / at the end, 404 error was returned (as in the screenshot below):

![screenshot](https://cloud.githubusercontent.com/assets/809530/7108252/517849c8-e1bb-11e4-8b8c-60ef90ea9900.png)

Is this behavior known?

**Comment by takezoe** [comment]
We've already got pull request #604 which is fixed this issue.
Should we take this pull request...?

**Comment by sylph01** [comment]
Sorry for creating a duplicate entry. PR #604 seems to address my problem. I'll wait for it to be merged (or patch my own instance with it). Thank you!
