### ISSUE TITLE
Comments in diff are sometimes not shown.

### ISSUE THREAD

**Issue by korombus** [takezoe/gitbucket#712]
Diffにコメントを記載した場合、一番上に来るDiffに書いたコメントが見えなくなる現象がありました。
「Ignore Space」にチェックを入れることで見えるようになることも確認しています。
ブラウザで要素を検証したところdivタグに「style="display: none;"」が入っていました。

https://github.com/takezoe/gitbucket/blob/3b7e6aa68e65c8ad664ca70a491c39e8890a8611/src/main/twirl/gitbucket/core/helper/diff.scala.html#L162
で、画面一番下の「Show line notes below」の表示/非表示をやってるんですが、その絞り込みが出来ていないようです。
https://github.com/takezoe/gitbucket/blob/3b7e6aa68e65c8ad664ca70a491c39e8890a8611/src/main/twirl/gitbucket/core/repo/commentform.scala.html#L62
のようにcomment-listの下のみにしないと表示されないようです。

**Comment by mrkm4ntr** [comment]
Thank you for reporting.
