### ISSUE TITLE
How to validate upgrades?

### ISSUE THREAD

**Issue by McFoggy** [takezoe/gitbucket#735]
Hello everyone,

_"This issue is not a defect and can be marked as question/discussion"_

We are investigating to use [gitbucket](https://github.com/takezoe/gitbucket) in my company. In such a process we'd like to know how others  have implemented an upgrade strategy of the system.
A SCM tool, like [gitbucket](https://github.com/takezoe/gitbucket), can quickly become quite critical ; thus just deploying the latest war looks like to be a little dangerous.

Can some of you explain how they deal with that?

PS: we understand that sources are "safe" in the way that an upgrade does not touch the git bare repositories, but nevertheless a non running front-end and http api in front can lead to a non productivity.

Thanks for your hints.

**Comment by takezoe** [comment]
Close all questions. If you have any questions about GitBucket, please send them to [the gitter room](https://gitter.im/takezoe/gitbucket) instead of issue according to [the Guideline for Issues](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md).
