### ISSUE TITLE
diffview is not defined

### ISSUE THREAD

**Issue by imunolion** [takezoe/gitbucket#757]
When I open a commit, gitbucket does not show diff.
Here is the error capture.

![diffview_is_not_defined](https://cloud.githubusercontent.com/assets/1018469/7646404/df1bcfd8-fafd-11e4-91a8-8de7d292b758.PNG)

**Comment by nazoking** [comment]
A `diffview` is defined by src/main/webapp/assets/vendors/jsdifflib/diffview.js
But the gitbucket doesn't use `diffview` since version 3.1.
Perhaps your browser loaded script from cache.
Please try 'super reload' push ctrl+f5.

**Comment by imunolion** [comment]
@nazoking 
Thanks!
In my case, super reload didn't fix problem but clear nginx cache.

**Comment by jaytaylor** [comment]
hard reload just fixed this for me, thanks!
