### ISSUE TITLE
Can not show blame view.

### ISSUE THREAD

**Issue by hikaruworld** [takezoe/gitbucket#773]
1. Show URL (`http://hostname:port/GROUP_NAME/APP_NAME/blob/HASH/fileName`)
2. click `Blame`
3. Can not show Blame View

* Chrome Inspector...

> Uncaught TypeError: Cannot read property '1' of null

It was OK if substituted as below .
```javascript
  function updateBlame(){
    /*var m = /^\/(blame|blob)(\/.*)$/.exec(location.pathname.substring(repository.length));*/
   // repository => http://hostname:port/group_name/app_name
   // location.href => http://hostname:port/group_name/app_name/blame/HASH/assets/FILE_NAME
   // location.pathname => /group_name/app_name
    var m = /^\/(blame|blob)(\/.*)$/.exec(location.href.substring(repository.length));
    var mode = m[1];
```

envirionment is..
* APPLICATION_ROOT `http://hostname:port/`
* GitBucket 3.3
* Chrome Version 43.0.2357.81(mac) and 43.0.2357.81 m(win) and InternetExplorer11

**Comment by ssogabe** [comment]
I have same issue.Chrome 42.0.2311.152

**Comment by takezoe** [comment]
@hikaruworld Applied. Thanks for your feedback!
