### ISSUE TITLE
GitBucket development setup - Question

### ISSUE THREAD

**Issue by FlYnN91** [takezoe/gitbucket#774]
Hi,

I've been using GitBucket and its been great. You guys are doing awesome job. I would like to see if I could participate in making some additions to the project in my spare time. Specifically, I'd like to extend the API functionalitty. I've been going through the Developer's Guide, but I am struggling to include the scalatra-forms. I've got the source and I've ran sbt in command-prompt, but the documentation isn't 100% clear to the new commers as to where to add the changes suggested.
Could anyone provide some guidance? I am looking to update the developer's guide to make it easier for people in similar situation like mine.

**Comment by aadrian** [comment]
+1

I would also like to know some more details about how to develop and also extend with plug-ins GitBucket! :).

Since there seems to be so many open issues with feature requests (and many of them seem to be better suited as a plug-in), maybe the community could help more if the entry would not be that steep.

**Comment by takezoe** [comment]
Developer's Guide is here. But we know it's not enough.
https://github.com/takezoe/gitbucket/tree/master/doc

In addition, plug-in system and API are still unstable. So we can not start documentation soon. But of course, we will provide it in the future.

**Comment by lefou** [comment]
+1 for documentation of the current (unstable) plug-in API.

I think, it's perfectly ok that the API is suspected to change as long as it is stated in the docs. But if nobody experiments with it because of lack of documentation, we won't get any feedback and the API will never get stable.

Nobody required a perfectly written book, but some bullet list covering the most important facts would be really helpful.

**Comment by FlYnN91** [comment]
By trial and error I have got most of the dependencies installed and I am working on a bullet point list of steps as well as common setup issues (as I've come across some) which I will share with everyone. I am just stuck at solving the scalatra-forms dependency. I got sources from the @takezoe 's repository, but not sure what to do with it and how to do it.

**Comment by bfritz** [comment]
@FlYnN91 Can you explain more about what's tripping you up with scalatra-forms?

Other than being in a separate Maven repo...which is configured in `project/build.scala` and should be handled transparently by sbt...it should be no different than any other dependency.  And I don't think scalatra-forms is used by any of the API code.  As long as sbt pulls down the binary JAR from @takezoe's repo you should be set to make changes within `gitbucket.core.api` while mostly ignoring scalatra-forms.

**Comment by FlYnN91** [comment]
@bfritz I've got it working. Woohoo!

**Comment by FlYnN91** [comment]
These are my steps to getting GitBucket running on a Windows local machine.
* Install [Java](http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html)
   * Ensure javac and java are accessible from command line
* Install [Scala](http://www.scala-lang.org/download/all.html)
* Install Scalatra
   * Download and Run [Conscript Executable JAR](https://github.com/n8han/conscript/releases/download/0.4.4-1/conscript-0.4.4-1.jar)
   * Add cs.bat to PATH
   * Install giter8 - in command line run cs n8han/giter8
* Install [sbt](http://www.scala-sbt.org/download.html)
   * Add Environment Variable GITBUCKET_VERSION with value 3.3
* Clone/Pull GitBucket repository
* Go to the repository folder, open command line.
* Depending on what you want to do choose one of the following set of commands from [Developer's Guide](https://github.com/takezoe/gitbucket/blob/master/doc/how_to_run.md)
   * Give couple of minutes to compile project and then visit http://localhost:8080

These steps worked for me very well. Hope it helps someone.

**Comment by lefou** [comment]
Huh, I'm on Linux, but I thought it is enough to have Java and sbt installed. No need to have a local installation of Scala or Scalatra or giter8. At least under Linux it's not needed.

**Comment by FlYnN91** [comment]
I did not test without them, but you may be right. If it works without them then that's even better.

**Comment by nazoking** [comment]
No need to have a local installation of sbt. gitbucket epository include sbt jar and sbt.sh ( and sbt.bat ).

**Comment by takezoe** [comment]
Close all questions. If you have any questions about GitBucket, please send them to [the gitter room](https://gitter.im/takezoe/gitbucket) instead of issue according to [the Guideline for Issues](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md).
