### ISSUE TITLE
Unable to manage collaborators for groups in 3.3

### ISSUE THREAD

**Issue by jeffgus** [takezoe/gitbucket#776]
I am pretty sure the previous version allowed me to add/remove users to a group -> repo -> settings -> collaborators.

**Comment by takezoe** [comment]
You can't manage collaborators for each group repository.  You can manage group members only. It applied to all group repositories.

**Comment by jeffgus** [comment]
Ah! Got it, yeah that makes sense.

**Comment by KekSfabrik** [comment]
any plans of adding that? we'd really like that functionality
logically it would fit our structures best if some people could manage a group of repos while others can work on _some_ of the repos in that group without being able to read _all_ the repos in that group

**Comment by takezoe** [comment]
Close all questions. If you have any questions about GitBucket, please send them to [the gitter room](https://gitter.im/takezoe/gitbucket) instead of issue according to [the Guideline for Issues](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md).
