### ISSUE TITLE
how to add group to a project

### ISSUE THREAD

**Issue by jeffsui** [takezoe/gitbucket#779]
sorry,I used to use gitbucket to handler my project in my pc.
but, I cant find one way to add group to a project.
please someone could tell me how do it?

**Comment by jeffsui** [comment]
sorry,I used to use gitbucket to handler my project in my pc.
but, I cant find one way to add group to a project.
please someone could tell me how do it?

**Comment by FlYnN91** [comment]
When you say project, do you mean a repository?

**Comment by jeffsui** [comment]
yes,I mean a repository.

**Comment by pcqpcq** [comment]
I don't think it's possible to add a group to a repo, even at github.
so, did you mean add a repository to a group?

you can change the owner of a repo when you are creating one.

**Comment by jeffsui** [comment]
oh,group I mean In some program team many developer are in there.
not github's group .

**Comment by FlYnN91** [comment]
I think what you would have to do is create a group called "Group A". Create a new repository "Project A" and make the "Group A" owner of the project. Then go to edit the "Group A" and add the developers you want. You can also add another group. If you have the developers already in a group e.g. "All developers", just add that group as a member. That should work.

**Comment by yoshinari-nomura** [comment]
> If you have the developers already in a group e.g. "All developers", just add that group as a member. That should work.

This is exactly what I want to do! But I could not find a way to do that from current (3.3) GitBucket UI...

For example, I have three groups `designer`, `developer`, and `manager`.  In that case, how can I bind these groups to a repository `ReposA` without expanding the group members flatly ?

As for GitHub, they allow us to add collaborators to a repository on team basis. Also they have
*organization* on the top of that.

**Comment by takezoe** [comment]
Close all questions. If you have any questions about GitBucket, please send them to [the gitter room](https://gitter.im/takezoe/gitbucket) instead of issue according to [the Guideline for Issues](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md).
