### ISSUE TITLE
how to release a project?

### ISSUE THREAD

**Issue by hcyxsq** [takezoe/gitbucket#783]
I tried click 'release', and then it only show me a blank 'tags' with no release buttom, how to release a project?

**Comment by hansgru** [comment]
You set a Tag with the GIT command. A tag is a release in GitBucket (but also in GitHub)

**Comment by takezoe** [comment]
@hcyxsq Mentioned about the release page? It's not implemented in GitBucket yet.

**Comment by takezoe** [comment]
Merged to #607

**Comment by kurdtpage** [comment]
To create a new release, use these commands:
```
git tag -a v0.1.1 -m "Release test"
git push origin v0.1.1
```
Now go into the Releases page.
Source: https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by TLingC** [comment]
@kurdtpage Thank you for your reply, but my issue has been raised for four years.

I know how to create a tag, but at that time, gitbucket doesn't seem to be able to set addition information of a release like github.
