### ISSUE TITLE
what is the http path of gitbucket repository

### ISSUE THREAD

**Issue by xyfigo** [takezoe/gitbucket#784]
I run a gitbucket on tomcat. I change the port of tomcat to 80, and change the default server context path to gitbucket.So I can access the gitbucket web page as following：
http://10.10.19.105

When I start to clone a gitbucket repository, troubles come:
git clone http://10.10.19.105/root/game-of -life.git 
fatal: repository 'http://10.10.19.105/root/game-of -life.git/' not found

I try a new path adding /git context which can work well:
git clone http://10.10.19.105/git/root/game-of -life.git 
Cloning into 'game-of-life'...
remote: Counting objects:1940, done
....
Checking connectivity,,, done

My question is why the git path is http://[host-name]:[port]/**git**/[user]/[repository name].git?

**Comment by takezoe** [comment]
This is a specification of GitBucket. GitBucket handles paths under /git as Git repository.

**Comment by xyfigo** [comment]
But in the right of  the repository main page, there are some words : 
HTTP clone URL 
You can clone HTTP or SSH. 
This HTTP URL is not the path using in "git clone" command. This is puzzling.Why not add /git to the clone URL?

**Comment by takezoe** [comment]
Hmm... This is an example on my GitBucket instance:
![repository_url](https://cloud.githubusercontent.com/assets/1094760/8247233/a6a79132-1687-11e5-963b-46f7975f3e8d.png)
Do you configure the base url of GitBucket correctly?

**Comment by xyfigo** [comment]
Sorry the HTTP URL is right. I miss the /git path because only part of the URL is visual.
Thanks for your patience!
