### ISSUE TITLE
Guide for H2 Console.

### ISSUE THREAD

**Issue by matrixbegins** [takezoe/gitbucket#790]
Its not really a bug. Just wanted a guide/wiki on H2 console. Whats the purpose. I noticed that they are majorly Databases in the saved settings. I am running gitbucket standalone. If I select ```Generic Mysql ``` and try to test a connection: 
I am getting ``` Class "com.mysql.jdbc.Driver" not found [90086-180] ```
Can someone explain primary purpose of this section and how to use it.

**Comment by takezoe** [comment]
Thanks. I wrote it on Wiki: https://github.com/takezoe/gitbucket/wiki/Connect-to-H2-database

**Comment by matrixbegins** [comment]
So I guess by default gitbucket stores everything on sqlite db?
How to store data in MySQL or any other db?

**Comment by takezoe** [comment]
One of GitBucket identities is JVM based application to make easy installation, so we can't choose sqlite as a default data store. However we have a plan to add multi db support to GitBucket. When it completes, you will be able to use MySQL as data store of GitBucket.
