### ISSUE TITLE
Allow proxy setting for building gitbucket

### ISSUE THREAD

**Issue by hansgru** [takezoe/gitbucket#800]
Please allow to specify a proxy setting for SBT when building it.

The ```sbt.bat``` and ```sbt.sh``` do not allow this.

Thank you.

**Comment by takezoe** [comment]
Environment variable `JAVA_OPTS` has been introduced in `sbt.sh` and `sbt.bat`. You can specify proxy through environment variable as following:
```
export JAVA_OPTS="-Dhttp.proxyHost=<host> -Dhttp.proxyPort=<port> -Dhttp.proxyUser=<user> -Dhttp.proxyPassword=<pass>"
```
