### ISSUE TITLE
Plugin: Do you have to build it for each new version of gitbucket?

### ISSUE THREAD

**Issue by uli-heller** [takezoe/gitbucket#804]
I've read https://takezoe.github.io/gitbucket/gitbucket/2015/06/29/how-to-create-plugin.html .

It says this:

> ...
> Notice: gitbucket-assembly must be a latest version.
> ...

Does this mean you have to build your plugin for each and every fresh version of gitbucket?
Currently, gitbucket is on version 3.4.0. So I'm using this for the gitbucket-assembly, run the build of my plugin and install the plugin into a gitbucket installation of version 3.4.0.

Next month, gitbucket will probably be on version 3.5.0. Can I install the plugin created against 3.4.0 or
do I have to edit the gitbucket-assembly and re-run the build?

Thanks for your help, Uli

**Comment by takezoe** [comment]
Currently, plug-in API is unstable, so plug-in jar which is compiled with old version of GitBucket might not work on the latest version of GitBucket (or reverse is also true). Therefore we recommend to rebuild your plug-in if you will upgrade GitBucket.

In fact, plug-ins which are compiled with GitBucket 3.4.0 probably work on 3.5.0. It's a possibility.

**Comment by lefou** [comment]
How about releasing the plug-in API as separate artifact and only depend on it in a plug-in project but not the whole gitbucket-assembly? That way, it would be more clear which version of gitbucket supports which plug-in version and vice versa.

**Comment by uli-heller** [comment]
Thanks for answering my question. So when I'm writing a plugin now,

* it could work in future version
* it could work in future versions after doing a new cimplile
* it could fail to recompile for future versions

Maybe it is best to wait for a while ;)

**Comment by takezoe** [comment]
@uli-heller Maybe that's right .
We are testing plug-in API in [gitbucket-gist-plugin](https://github.com/takezoe/gitbucket-gist-plugin). We will also create some plug-ins as practical example in the future other than it. You can know plug-in API status by checking them.

**Comment by uli-heller** [comment]
Thanks a lot. I really do appreciate your work and your support.
I'll throw an eye on the gist plugin.

Best regards, Uli
