### ISSUE TITLE
Turn on logging

### ISSUE THREAD

**Issue by FlYnN91** [takezoe/gitbucket#805]
Hi all,

So I've got Gitbucket (gitbucket.war) running on IIS with Jetty 8. I've turned on Jetty logging, but I cannot find any information how to log stuff from GiBucket. What am I missing? 

Thanks

**Comment by takezoe** [comment]
GitBucket uses LogBack via SLF4J and outputs all logs to stdout in default.
You can give LogBack configuration from outside of GitBucket.
See details about LogBack configuration at: http://logback.qos.ch/manual/configuration.html

But unfortunately, I don't know how to give arguments to the application on Jetty8 on IIS.

**Comment by FlYnN91** [comment]
Thanks for the response @takezoe , I will look into this.
