### ISSUE TITLE
How can review board access the history of file?

### ISSUE THREAD

**Issue by KenLau** [takezoe/gitbucket#806]
Hey, guys, we are trying to use review board with gitbucket, however, we found that we cannot access the history of the file like the following git services:
cgit: http://git.gnome.org/browse/gtk+/plain/<filename>?id2=<revision>
Gitweb: http://git.kernel.org/?p=bluetooth/bluez-gnome.git;a=blob_plain;f=<filename>;hb=<revision>

We can only access the history of the file with the following gitbucket url
https://<gitbucket host name>/<group name>/<project name>/blob/<revision>/<filename>?raw=true
but this url use https and review board failed to access this file
is there any other ways to access the history of the file with gitbucket?

**Comment by takezoe** [comment]
> but this url use https and review board failed to access this file

Why reviewboard fails to access https url?

**Comment by KenLau** [comment]
I have no idea why, but it just happens, haha, anyway, have you tried to use review board with gitbucket?

**Comment by takezoe** [comment]
No, I've never used reviewboard.
I think reviewboard can't access GitBucket whether GitBucket  provides other url to access file content if reviewboard fails on https.
Could you try on http?

**Comment by KenLau** [comment]
Yup, i have tried the http version, however, still cannot access the file history

**Comment by takezoe** [comment]
Hmm... I don't know about reviewboard well, so I can't suggest a way to resolve this issue. Could you provide additional information such as: 
- Is your repository on GitBucket public? or private?
- Do you allow anonymous access to GitBucket?
- Are there any error messages in reviewboard log?

**Comment by KenLau** [comment]
1, private
2, no
3, the only error message from reviewboard is [The file was not found in the repository. (HTTP 400, API Error 207)], it means that reviewboard cannot access the file, because of http connection timeout. The detailed log is in the server, i will ask my colleague for that, see if he captured the logs or not

Thank you very much, Takezoe. :D

**Comment by KenLau** [comment]
1, private
2, no
3, the only error message from reviewboard is [The file was not found in the repository. (HTTP 400, API Error 207)], it means that reviewboard cannot access the file, because of http connection timeout. The detailed log is in the server, i will ask my colleague for that, see if he captured the logs or not

Thank you very much, Takezoe. :D

**Comment by KenLau** [comment]
Btw, is there any code review tools for GitBucket?

**Comment by McFoggy** [comment]
> Btw, is there any code review tools for GitBucket?
Isn't `Pull-Request` workflow something that would suffice to your case?

**Comment by KenLau** [comment]
@McFoggy Pull-Request is good option for us, however, we found that there are some performance issues for some of our projects, they take quite a long time to open the project page, some of them even reach the error of request timeout. Therefore, we cannot use pull-request properly with our gitbucket server. As a result, we need to establish a code review service for our own projects, and now we are researching Review Board and gerrit (but personally, i like the UI of review board :D)

**Comment by takezoe** [comment]
@KenLau It needs the authenticated session (not basic authentication) to access the private repository page. I think GitBucket have to support basic authentication to access from scripts or any other external tools such as reviewboard.

It's raised in https://github.com/takezoe/gitbucket/issues/430 and we are considering about it.

**Comment by KenLau** [comment]
Nice, thank you very much. how long do you need to finish this task? :D we are looking forward seeing your message!

**Comment by takezoe** [comment]
Close all questions. If you have any questions about GitBucket, please send them to [the gitter room](https://gitter.im/takezoe/gitbucket) instead of issue according to [the Guideline for Issues](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md).
