### ISSUE TITLE
Any environment variables that could force to change the home directory?

### ISSUE THREAD

**Issue by cia48621793** [takezoe/gitbucket#809]
I was trying to deploy GitBucket with Tomcat in OpenShift, however, as of the very default home directory location is ~/.gitbucket, and ~/ is resolved as "/var/lib/openshift/{ID}", which is unable to write anything by the user.
I used to change HOME_DIR variable to "~/app-root/.gitbucket" but still no luck, maybe I should try editing the Tomcat configuration file itself?

**Comment by takezoe** [comment]
See this document: https://github.com/takezoe/gitbucket/blob/master/doc/directory.md

**Comment by cia48621793** [comment]
Seems like I have lost one doc or two. Thanks for helping!
