### ISSUE TITLE
Lose metadata when the process oom

### ISSUE THREAD

**Issue by zxhdaniel** [takezoe/gitbucket#817]
Yesterday, I came across a problem that when the gitbucket process(tomcat) oom,  some metadata such as user info, repositories is lose!!!

It is such a big problem, but i have no idea what happened.

There are some screenshots of error log, i hope it can help.

![1a594e09-c745-4a8e-bcd6-55f267dbeac4](https://cloud.githubusercontent.com/assets/2572041/8543798/5a709b52-24d2-11e5-8f7a-b62346e27b38.png)
![3f1dc870-f355-4c31-a101-ce6156c65285](https://cloud.githubusercontent.com/assets/2572041/8543801/5d4309f0-24d2-11e5-9176-e74b1eefe12c.png)
![ec016b42-1db4-4cc8-ad00-c223f0a1a1b1](https://cloud.githubusercontent.com/assets/2572041/8543804/604bb412-24d2-11e5-8ba5-2d3fc1983870.png)
![fc696c8e-2630-450e-ab21-9ace4909f96d](https://cloud.githubusercontent.com/assets/2572041/8543806/628ebaa8-24d2-11e5-93bb-8a0902f9753d.png)

**Comment by takezoe** [comment]
Did you restart Tomcat after OOM?

**Comment by zxhdaniel** [comment]
yes.

**Comment by takezoe** [comment]
Close all questions. If you have any questions about GitBucket, please send them to [the gitter room](https://gitter.im/takezoe/gitbucket) instead of issue according to [the Guideline for Issues](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md).
