### ISSUE TITLE
Truncate long commit messages

### ISSUE THREAD

**Issue by trymnilsen** [takezoe/gitbucket#820]
Hi there

A small suggestion for improvement would be adding some small snippets of CSS to truncate long commit messages. 

Example
![image](https://cloud.githubusercontent.com/assets/1550685/8591178/caf46458-2626-11e5-9b8d-b32cab02246d.png)

How github does it (not that we need to directly copy it).
![image](https://cloud.githubusercontent.com/assets/1550685/8591199/ec8e928c-2626-11e5-98cd-212c9ba0e730.png)

**Comment by McFoggy** [comment]
@takezoe this issue has been solved via PR and c
