### ISSUE TITLE
Windows Instructions don't work.

### ISSUE THREAD

**Issue by ChaseFlorell** [takezoe/gitbucket#827]
I'm trying to install using the [Windows Instructions](https://github.com/takezoe/gitbucket/wiki/Installation-on-IIS-and-Helicontech-Zoo) however the Helicontech-Zoo WPI is broken. It is throwing a 404 when trying to install Jetty.

Now I realize that this is outside your control, however I'm wondering if there are alternative instructions on how to install GitBucket on a Windows Server? I have near zero experience with anything Java related.

![Imgur](http://i.imgur.com/0GSibiu.png)

**Comment by extreme-dh** [comment]
I had the same
Try to download Jetty 7 & 8 from http://download.eclipse.org/jetty/
Then unpack them to c:\jetty7 and c:\jetty8 and run Helicontech-Zoo again.
This solved 404 problem for me, the rest should work as in description

**Comment by ChaseFlorell** [comment]
@extreme-dh thanks for the quick reply. The zip folder is nested.

  - jetty.bundles.repo -> target -> site 
     - features\
     - META-INF\
     - plugins\
     - artifacts.jar
     - content.jar
     - site.xml

So what is the "root directory" of the jetty bundle? What should the `jetty7` and `jetty8` directory look like?

**Comment by ChaseFlorell** [comment]
Actually, it looks like I followed the wrong links to get jetty 7/8

Here's the archives.

 - http://archive.eclipse.org/jetty/8.1.9.v20130131/dist/
 - http://archive.eclipse.org/jetty/7.6.9.v20130131/dist/

**Comment by extreme-dh** [comment]
That's right, the propper zip file should look like this:
![1](https://cloud.githubusercontent.com/assets/5195296/8635350/98107752-281f-11e5-8fea-b0061c2992c7.png)

**Comment by ChaseFlorell** [comment]
I have it working now using the links I posted. Wonder if we should update the WIKI.

**Comment by ChaseFlorell** [comment]
Are there additional dependencies that don't come by default with jetty?

When I spin up the app, I get a 500

>  java.io.FileNotFoundException: Unable to find XML Config: etc/jetty-hightide.xml

So I found the `jetty-hightide.xml` on github, and copied it into the etc folder (might not be the right way to go, but it gets rid of the error).

After doing that, I run it again and get 

> No such OPTIONS: jdbc

Now I know the issue is PEBKAC but I honestly don't know where to go with this. Is there any magic sauce to getting this going?

**Comment by extreme-dh** [comment]
Yeah, got one too.
I totally forgot - you need to download somewhere whole jetty-hightide distribution.
As I remember jetty8 will be enough. Try this http://mvnrepository.com/artifact/org.mortbay.jetty/jetty-hightide

**Comment by ChaseFlorell** [comment]
Ah, gotcha. I sniped the .zip file from [here](https://www.versioneye.com/java/org.mortbay.jetty:jetty-hightide/8.1.4.v20120524), but it does seem to be a little out of date. At least it works.
