### ISSUE TITLE
"checklist [x]" or "<strike>"  on readme.md don't work?

### ISSUE THREAD

**Issue by thearabbit** [takezoe/gitbucket#830]
I want to write `readme.md` with `checklist [x]` and `~~strike~~`.
But not work.
Please help me.

**Comment by takezoe** [comment]
1. GitBucket supports checklist at only contents of issue and pull request. It's not available at other places.
2. Strike syntax is not supported by pegdown which is markdown parser GitBucket used. However the recent version of pegdown supports strike syntax, so we'll try to upgrade pegdown.

**Comment by takezoe** [comment]
Strike syntax will be available in the next version of GitBucket.

**Comment by thearabbit** [comment]
Thanks for your reply.
