### ISSUE TITLE
how to define the ssh url that display on webui?

### ISSUE THREAD

**Issue by raindylong** [takezoe/gitbucket#832]
Hi all,
ssh port is listening on 3222(use git  os account to start gitbucket, so can not listen on port 22) , and I use root to run a tcpproxy to forward port 22 ---> port 3222 ,
so there are tow questions:
(1) how to define the ssh url display on webui such as ssh://abc@abc.com/abc/abc.git but not ssh://abc@abc.com:3222/abc/abc.git ?
(2) how to define ssh port just bind on one interface IP but not 0.0.0.0 ?

![bucket](https://cloud.githubusercontent.com/assets/1438526/8675515/f614f86a-2a76-11e5-84fe-a379b07d9efa.png)

**Comment by takezoe** [comment]
Both of (1) and (2) are impossible in the current version of GitBucket. But it might be possible to rewrite URL in the box by plug-in. GitBucket plug-in can insert any JavaScript like GreaseMonkey.

**Comment by takezoe** [comment]
Close all questions. If you have any questions about GitBucket, please send them to [the gitter room](https://gitter.im/takezoe/gitbucket) instead of issue according to [the Guideline for Issues](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md).
