### ISSUE TITLE
Recovery from lost git repo

### ISSUE THREAD

**Issue by wangzk** [takezoe/gitbucket#837]
I removed one repository by mistake and now I want to recovery that repo.
I have used a file recovery tool to find that repo directory back.
For example, I get the directory "XXX.git" back. But under this directory, there is no other files but only config, HEAD, hooks and so on.
How can I get all my source code files back from this directory?
How to make that "XXX.git" directory as a standard git directory?

Thank you very much!

**Comment by McFoggy** [comment]
gitbucket git repositories are `bare` repositories : you do not see their content directly in the file system.
If you recovered the bare repository files then you have all you need to recreate properly the repository in gitbucket.

The cleanest solution would be (in my opinion) to:
- move the recovered repository elsewhere on your disk
- clone the recovered repository locally
- recreate the project & repository in gitbucket (create it EMPTY !)
- push the clone to the recreated project

**Comment by wangzk** [comment]
@McFoggy 
Thank you for your help! I finally recovered my repo. I record the steps below:
1. Assuming that I recover the bare repo "XXX.git" into the local directory "E:/XXX.git"
2. first, clone the recovered repository locally. For example, I want to clone the repo to "D:/workspace", then I can run the command: "cd D:/workspace" && "git clone E:/XXX.git". Then a new directory "XXX" will appear under the "D:/workspace".
3. Just create a new EMPTY repository in gitbucket.
4. Follow the guide on gitbucket to "git remote add" and "git push".
5. Finally, the repo is on gitbucket again!

**Comment by McFoggy** [comment]
Cool, close the issue if you have resolved your problem.
