### ISSUE TITLE
Restarted Gitbucket can't find existing users and repos

### ISSUE THREAD

**Issue by paulocoghi** [takezoe/gitbucket#840]
I have a Gitbucket 3.4 instance that perform perfectly, with many users, repos and groups.

But, when I restart the Gitbucket process (executing it again after a `kill`), I am not able to login with the same credentials anymore, although the files in `.gitbucket/` are still there with everything we have done.

I realized that it can't find existing users and repositories because I could login with the old `root`/`root` login/password and, in the admin area, no user or repository was displayed (also I had changed root's password before the restart).

### System Details
___

Ubuntu 14.04 64bits (fresh install, with Apache completely removed)
Gitbucket 3.4
Java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

### How to reproduce the bug:
___

**1. Execute Bitbucket without servlet container, with:**
`java -jar gitbucket.war --port=8080 --host=gitbucket.your-domain.net`

**2. Access the instance with `http://gitbucket.your-domain.net:8080`**
Login and create some users and repos

**3. Change your root password**
Doing this you will be able to test if this bug ocurred using the default root password

**4. Kill the Gitbucket process**
In my case, I used `ps ax | grep gitbucket` to identify the process id and `kill [id]` to kill it

**5. Restart Gitbucket with:**
`java -jar gitbucket.war --port=8080 --host=gitbucket.your-domain.net`

**6. Try both root's password, new and old**
If the bug occurs, you will only be able to login with old `root`/`root` and will not see users in admin area

**Comment by takezoe** [comment]
Check `~/.gitbucket/`. Are there any directories under `~/.gitbucket/repositories/`?

**Comment by paulocoghi** [comment]
Yes, all our repositories are there, including `.git` and `.wiki.git` files.

**Comment by takezoe** [comment]
Hmm... Could you check h2 data too? https://github.com/takezoe/gitbucket/wiki/Connect-to-H2-database

**Comment by paulocoghi** [comment]
I will do it right now.

**Comment by paulocoghi** [comment]
Exactly, the H2 data is wrong. I am trying now to correct it again. No clue about how Gitbucket forgets its credentials.

![gitbucket_h2](https://cloud.githubusercontent.com/assets/378397/9064717/2a89778c-3aa4-11e5-96f4-2573578be00c.png)

**Comment by takezoe** [comment]
JDBC URL in your screenshot seems wrong.

**Comment by paulocoghi** [comment]
Sorry for the post above. In fact, I can connect using:

- Driver Class: org.h2.Driver
- JDBC URL: jdbc:h2:~/.gitbucket/data
- User Name: sa
- Password: sa

There are only the `root` user in `Account` table and no repositories in `Repository` table. Strangely the repositories files are still there in `./gitbucket`

**Comment by paulocoghi** [comment]
My concern is if all the data will be lost again if, for example, I need to reboot the server.

**Comment by paulocoghi** [comment]
I restarted it again and my changes were not lost this time. I think that the best option is to close the issue for now.

**Comment by takezoe** [comment]
No problem. I can't say why your database was cleared. Please try same operation again and report result if it's possible.

**Comment by paulocoghi** [comment]
I will try with one step that I have not mentioned before, the hostname change.

**Comment by paulocoghi** [comment]
No errors or undesired effects this time. I have killed the current Gitbucket instance, restarted it again with a new hostname and all the (new) changes are intact.

**Comment by takezoe** [comment]
Good news. I strongly recommend that you take a backup. https://github.com/takezoe/gitbucket/wiki/Backup

**Comment by paulocoghi** [comment]
Thanks for remember! Since I will be in production for now on, backups will be a must have. :)
