### ISSUE TITLE
Style vs github

### ISSUE THREAD

**Issue by garygreen** [takezoe/gitbucket#851]
Out of interest how closely should gitbucket mimic the style of github? I notice there is a lot of inconsistencies with paddings, sizes, colours (buttons too small, minimal paddings, etc).

Are you guys willing to accept PRs to make all the areas match the same polish that github has? :smile:

**Comment by hansgru** [comment]
+1 for more polish.

**Comment by takezoe** [comment]
@garygreen Yes, we will take such pull requests.

In addition, GitHub UI is always changing, but we can't catchup them soon. Therefore there are many differences between GitBucket and GitHub appearance now. Maybe we should move to Primer from Bootstrap2. And current GitBucket style definition depends on style attribute to override Bootstrap styles. We want to cleanup these styles and refactor CSS. Pull requests which make them are welcome!

**Comment by garygreen** [comment]
I suppose it makes sense to use Primer, only thing I don't like about it is the grid system (not a fan of `one-fifth`, `.three-fourths`, `two-thirds` style, much prefer bootstrap 3's numeric system `col-sm-3` `col-lg-6`.

To be honest, it shouldn't be too difficult to get near identical style to github by compiling own bootstrap 3 with some custom variables, some overrides and adding some bootstrappy stuff.

**Comment by hansgru** [comment]
+1 for using bootstrap 3.

**Comment by takezoe** [comment]
Merged with #881
