### ISSUE TITLE
Add an announcement mechanism

### ISSUE THREAD

**Issue by McFoggy** [takezoe/gitbucket#852]
It would be great to have a way to notify users/groups for some announces.

Announces could:

- be persistent or not
- be notified by email or not
- have a scope target
    - global
    - list of group
    - list of individuals
- ...

For persistent announces, we could imagine to provide some panels in different places showing the announces relatively to the place we are on the site: main page, project page.

One of the first usage would be to announce: shutdown, upgrade, restart in advance to gitbucket users.

Such a mechanism could also serve as a basis for a kind of messaging system between individuals/groups.

_PS: of course we can split this issue in several smaller ones in order to deliver something step by step._

This could be implemented as a plugin also, but I am not sure we have ways today to add content from a plugin into existing gitbucket pages.

**Comment by takezoe** [comment]
GitBucket has a simple notification panel at the top of right sidebar. Yes, I guess the more rich notification system you mentioned should be provided as plugin because notification requirement depends on usecase. We will provide more practical document about plugin development.

**Comment by McFoggy** [comment]
> GitBucket has a simple notification panel at the top of right sidebar
Other than the flash notification? 
I updated on 3.4 and didn't saw any new panel for notification.

If the plugin mechanism allows enough extensibility (meaning enrichment of existing pages) then it will be a perfect candidate to develop this functionality as a plugin. 
Meanwhile for my own needs I'll probably create a small page to be able to email all users when a shutdown/upgrade/restart is planned.

**Comment by McFoggy** [comment]
For those interested and waiting for something better, I have created in my branch [add-email-announces](https://github.com/McFoggy/gitbucket/tree/add-email-announces) a "mailing" facility so that you can inform all your active users about a next shutdown/upgrade

![image](https://cloud.githubusercontent.com/assets/1119660/9006590/7d0c5c7c-3789-11e5-8bdc-19320f98693d.png)

Enter a subject, a text description and an email announce will be sent to all active users of the system. Emails are sent via usage of BCC email field.

**Comment by McFoggy** [comment]
Rebased on #4a35b65c2c

**Comment by takezoe** [comment]
Cool.

> If the plugin mechanism allows enough extensibility (meaning enrichment of existing pages) then it will be a perfect candidate to develop this functionality as a plugin. 

I expect it's possible to implement as a plug-in. However we might have to add some new extension point to make this plug-in. For example, now we can add an item to existing menu by JavaScript as GreaseMonkey script. I think it's better that we can add an item via plug-in API.

**Comment by McFoggy** [comment]
@takezoe I saw how you integrated [gist plugin](https://github.com/takezoe/gitbucket-gist-plugin) and how GreaseMonkey works. But relying on such [augmented browsing](https://en.wikipedia.org/wiki/Augmented_browsing) capabilities introduce an invisible API dependency between the application and the plugin which relies in fact in the naming/construction of the html page and CSS selectors to plug the functionality into the application.

If it is clear that introducing such mechanisms means also __stability__ in the page design, then let's jump into it. If tomorrow you want to do #851, it will probably mean reconstruct the page layout and then break plugins.

I am not against that way and the weak dependencies it implies ; I just wanted to clarify that point.

Having that in mind, I'll give the plugin mechanism a try for this announcement extension.

**Comment by McFoggy** [comment]
Following your advices, I have created [McFoggy/gitbucket-announce-plugin](https://github.com/McFoggy/gitbucket-announce-plugin).

It was quite easy to turn the feature into a plugin ; but it requires #861 to be integrated first.

**Comment by McFoggy** [comment]
I am closing the issue. 

People interested into the feature can now use [McFoggy/gitbucket-announce-plugin](https://github.com/McFoggy/gitbucket-announce-plugin).

**Comment by takezoe** [comment]
@McFoggy Great plugin! I made a plugin list in README.md and added your plugin: https://github.com/takezoe/gitbucket/blob/master/README.md#plug-ins

**Comment by McFoggy** [comment]
@takezoe thanks
