### ISSUE TITLE
Distinguish database version & application version

### ISSUE THREAD

**Issue by McFoggy** [takezoe/gitbucket#853]
It would be nice to see in the brand panel DB version and the application version:
`db:3.4  app:3.4-McFoggy-001`
where the later would be extracted from a file put in the classpath during the build and taken up from GITBUCKET_VERSION environment variable.

**Comment by takezoe** [comment]
Originally, I think GitBucket should not be active if app version and database version are different. That means migration failed.

**Comment by McFoggy** [comment]
@takezoe currently, in my company we are running gitbucket with db version 3.5 and app version: 3.5.0-AM-02. This means that we have an adapted version of the application. 

Even for gitbucket itself, it could be  _normal_ to my point of view to have for example a db version of 3.5 and an app version of 3.5.4. This just means that you have some minor updates of the application running in front of the major DB version.

Such a mechanism allows you to _patch_ the official major release with either:

- your own enhancements
- PR coming from other not yet integrated in a release
- rebase from master to introduce, before a major release, some enhancements, patches or fixes

Knowing the exact application version your are running does not look uncommon.

**Comment by McFoggy** [comment]
Now that the plugin mechanism is there this distinction is less necessary now.
I close the issue and the corresponding PR.
