### ISSUE TITLE
efficient way to develop plugins

### ISSUE THREAD

**Issue by McFoggy** [takezoe/gitbucket#863]
Hi,

when developing gitbucket, the auto reload mechanism as explained in the [how to run](https://github.com/takezoe/gitbucket/blob/master/doc/how_to_run.md#for-developers) doc is very efficient.

Is there a way to launch a dev version of gibucket to have the same kind level of feature for plugin development? Copy paste the plugin jar and restart gitbucket application is not what I would call efficient.

**Comment by takezoe** [comment]
Agree. We need efficient way to develop plugins. We want to consider about it in #822.
