### ISSUE TITLE
location.href not valid in function updateBlame()

### ISSUE THREAD

**Issue by ccskoba** [takezoe/gitbucket#864]
src/main/twirl/gitbucket/core/repo/blob.scala.html
```
154  function updateBlame(){
155	    var m = /^\/(blame|blob)(\/.*)$/.exec(location.href.substring(repository.length));
```

"location.href" is like a "http://xxxxx/path/name".
so, it should be "location.pathname".

Best Regards,

**Comment by pibi** [comment]
Should work if you set the Base URL on the System Settings. 

This bug is a duplicate of #781
