### ISSUE TITLE
where is rest apis docs?

### ISSUE THREAD

**Issue by pinghe** [takezoe/gitbucket#868]
like  'https://confluence.atlassian.com/display/BITBUCKET/Use+the+Bitbucket+REST+APIs'

**Comment by McFoggy** [comment]
gitbucket exposes some github API v3 if I am not mistaking (https://developer.github.com/v3/).

For the moment I do not know a doc page on that, you can perhaps start one. Look at the controller classes in the source code, some must implement those github endpoints.

**Comment by nazoking** [comment]
I write it https://github.com/takezoe/gitbucket/wiki/API-WebHook

**Comment by takezoe** [comment]
@nazoking Good job! Thanks a lot.

**Comment by McFoggy** [comment]
@pinghe good job
