### ISSUE TITLE
Very Slow pull request

### ISSUE THREAD

**Issue by TomMurakami** [takezoe/gitbucket#870]
I'm using version 2.0 of gitbucket.
When you press the pull request in gitbucket, even after forever does not process is complete.

**Comment by takezoe** [comment]
At first, 2.0 is so old. You should upgrade GitBucket to the recent version if it's possible.

Next, Does it reproduce with all pull requests? (for example, both of small and large pull requests)

**Comment by TomMurakami** [comment]
Thanks for your answer.
There is a request that does not complete a normal request, regardless of the size.

You may want to check before you upgrade to the latest GitBucket.
If you upgraded the GitBucket to the latest, or will not affect the source we are managing now of 2.0?
By upgrading, or there is no case of such source is broken?
Please tell me if there is a thing to be aware of if you want to another to upgrade from 2.0.

ご回答ありがとうございます。
（pull Requestsの）サイズに関わらず正常なリクエストと完了しないリクエストがあります。

GitBucketを最新にアップグレードする前に確認したいことがあります。
GitBucketを最新にアップグレードした場合、今の2.0で管理しているソースに影響はないでしょうか？
アップグレードすることによって、ソースが壊れるなどの事例はありませんか？
他にも2.0からアップグレードする場合に注意することがあれば教えてください。

**Comment by takezoe** [comment]
ソースではなくH2のマイグレーションに失敗するという話は何度か聞いていますので、アップグレード時に必ずバックアップを取っておくことをおすすめします。アプリケーションサーバ停止後に.gitbucketディレクトリを丸ごとコピーしておけば、アップグレードに失敗した場合でもwarと.gitbucketディレクトリを元のものに置き換えることで元に戻すことができます。

また、マイグレーションはGitBucketの起動時に自動的に行われますが、2.0からですとかなり差分がありますので時間（マシンのスペックにもよりますが数分程度）がかかる可能性があります。この間ユーザがGitBucketにアクセスしないことが望ましいです。万全を期すのであれば、ユーザが使用していない時間帯であったり、いったんリバースプロキシから切り離すなどしてアップグレードを行うのがよいかと思います。

また、アップグレード後はCSSやJavaScriptのキャッシュで一部の画面のデザインや動作がおかしくなってしまうケースがありますが、その場合はブラウザのキャッシュを削除してみてください。

アップグレード時の注意点としては以上になります。

**Comment by TomMurakami** [comment]
返信が遅くなりました。
ご回答ありがとうございます。

本件の原因は、MACで作成したソース名にWindowsの禁則文字が含まれている状態で
プルリクエストしたためでした。

**Comment by takezoe** [comment]
Close all questions. If you have any questions about GitBucket, please send them to [the gitter room](https://gitter.im/takezoe/gitbucket) instead of issue according to [the Guideline for Issues](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md).
