### ISSUE TITLE
Reset root/admin password

### ISSUE THREAD

**Issue by kosli** [takezoe/gitbucket#872]
How can i reset the password of the root/admin user? As i have forgot the password that i set orignially before changing to LDAP authentication.

**Comment by McFoggy** [comment]
One solution could be to connect to the DB using an external DB browser like [squirrel](http://squirrel-sql.sourceforge.net/) and reset the admin password

**Comment by kosli** [comment]
what database type is the "data.mv.db" ? do I need to run it with a "database server" before i can open it with squirrel or does it work simliar to sqlite?

**Comment by McFoggy** [comment]
Gitbucket uses a H2 database. Gitbucket when running acts as DB server but for itself (in memory process database). 
If you stop gitbucket, then you can launch a DB browser like squirrel using the gitbucket database files.
See the h2 docs for defining the jdbc URL to use depending on how you setup gitbucket: http://www.h2database.com/html/features.html § Database URL Overview.
Gitbucket does not modify the DB user & password, so sa/sa should work.

**Comment by McFoggy** [comment]
If you use for example squirrel as I suggested.

- download h2 db jar from http://repo2.maven.org/maven2/com/h2database/h2/1.4.180/ (it is the version used by gitbucket)
- open squirrel 
- edit the h2 embedded driver, add the h2 jar to the classpath
![image](https://cloud.githubusercontent.com/assets/1119660/9195978/40e8beec-4027-11e5-9e6d-bb79b19f8a32.png)

- once done, create an alias to connect to gitbucket db
![image](https://cloud.githubusercontent.com/assets/1119660/9195990/5cd1cc5c-4027-11e5-8730-eabc57a3d700.png)

- then you can do whatever you want in pure SQL
![image](https://cloud.githubusercontent.com/assets/1119660/9196008/86412452-4027-11e5-98d5-462403e6c5cd.png)

- to reset the password of root user to `root`, execute the follwoing SQL statetement

```
update account set password='dc76e9f0c0006e8f919e0c515c66dbba3982f785' where user_name = 'root';
```

**Comment by kosli** [comment]
Thank you very much McFoggy, it worked like a charm.

**Comment by McFoggy** [comment]
@kosli you're welcome

**Comment by McFoggy** [comment]
I do not know, the table still exists so you might not be correctly connected.
On the other hand, as the passwords are stored differently now in latests versions of gitbucket, the above SQL update command will not work anymore. 

Please use the gitter room (https://gitter.im/gitbucket/gitbucket) to express your problem.
