### ISSUE TITLE
create pull request bug

### ISSUE THREAD

**Issue by superhj1987** [takezoe/gitbucket#874]
When I update the gitbucket to the newest version, some things happen.

repository A;
user a and b;
A belongs to user a;
b fork A;

When I create a pull request: 
base is b:A  and from is a:A,then a page displays  "Not Found".

the url is : 

http://git.etouch.cn/gitbucket/A/a/compare/B:master...A:master

Is this a bug?

Hope a fast reply.

**Comment by takezoe** [comment]
Pull request will be improved and fixed a lot of bugs in GitBucket 3.6 which is the next release of GitBucket. So I expect this issue will be solved in 3.6.

**Comment by superhj1987** [comment]
OK,expect 3.6 is comming soon.....
