### ISSUE TITLE
Doubled URL in project RSS feed on gh-pages

### ISSUE THREAD

**Issue by HairyFotr** [takezoe/gitbucket#875]
I didn't know where to put this, but it bugged me a bit on every new post :)

In the RSS feed for the project (here: https://takezoe.github.io/gitbucket/feed.xml ), the URLs are doubled. For the latest release post it's: https://takezoe.github.io/gitbuckethttps://takezoe.github.io/gitbucket/gitbucket/2015/08/01/gitbucket-3.5.html

I'm guessing this is the template that needs fixing: https://github.com/takezoe/gitbucket/blob/gh-pages/feed.xml

**Comment by takezoe** [comment]
@HairyFotr Thanks for your feedback. I will fix as soon as possible.

**Comment by takezoe** [comment]
Fixed
