### ISSUE TITLE
Importing .bacpac file to azure from on-premise.

### ISSUE THREAD

**Issue by satyaprakashaw28** [takezoe/gitbucket#876]
@takezoe 
I used Microsoft SQL Server managment studio 2014 to upload .bacpac to azure from on premise network. All the steps for uploading the data has been done successfully, only the last part is showing error. 
![1](https://cloud.githubusercontent.com/assets/13770189/9233035/7a7ae3ce-414e-11e5-8370-75ba7324ff28.PNG)
![capture](https://cloud.githubusercontent.com/assets/13770189/9233040/7ea6bec8-414e-11e5-9918-6589bac3f7f2.PNG)

**Comment by takezoe** [comment]
I don't know a tool you mentioned. What does it related to GitBucket?

**Comment by satyaprakashaw28** [comment]
@takezoe 
It's ok.
