### ISSUE TITLE
Auto merge source code without accepting from ower.

### ISSUE THREAD

**Issue by du-tran** [takezoe/gitbucket#877]
Hi! I'm forking from another repository. After I made a pull request, I can automatically merge this code to origin repository without accepting from ower. Is this a bug ?
This is in 3.4 version, and was it fixed in 3.5 version ?

**Comment by takezoe** [comment]
I can't reproduce this issue. Does your account have an administration role? Administrators have a read and write permission for all repositories.

**Comment by takezoe** [comment]
Are there anyone who can reproduce this issue?

**Comment by du-tran** [comment]
Red area is my account. It's set to the normal account but I can auto merge my source code after make a pull request.
![default](https://cloud.githubusercontent.com/assets/5662000/9302139/2cf1d6f2-450f-11e5-9544-46a1e68526cb.png)

**Comment by takezoe** [comment]
@du-tran Merge button is displayed for only collaborators (who have write permission):
https://github.com/takezoe/gitbucket/blob/master/src/main/twirl/gitbucket/core/pulls/conversation.scala.html#L58

And also actual merge request is accepted from only collaborators:
https://github.com/takezoe/gitbucket/blob/master/src%2Fmain%2Fscala%2Fgitbucket%2Fcore%2Fcontroller%2FPullRequestsController.scala#L206

Could you show us more detailed information about repositories and users of your situation? Note that if your account is added to the group, your account has write permission to all group repositories.

**Comment by du-tran** [comment]
@takezoe : Thanks for your information. TYes, this is my setting mistake. I set this account to the collaborator group...
