### ISSUE TITLE
Deleting a commit's content will make a NullPointerException

### ISSUE THREAD

**Issue by du-tran** [takezoe/gitbucket#878]
In 3.4 version ,I make a new pull request, I want to delele some unneeded files. When i put "Commit Changes" button, i'll make a NullPointerException.

![step1](https://cloud.githubusercontent.com/assets/5662000/9243642/ed350c3a-41cd-11e5-9edf-ac7b3036e1af.png)
![step2](https://cloud.githubusercontent.com/assets/5662000/9243644/ed38a5d4-41cd-11e5-8588-ccbc0c0b7ff3.png)
![step3](https://cloud.githubusercontent.com/assets/5662000/9243643/ed38229e-41cd-11e5-955d-6b2dcfa370e7.png)

Was it fixed in new version ?

**Comment by takezoe** [comment]
GitBucket can't delete (and also update) files at the specific revision on the repository viewer because it makes a new branch. Therefore we hide the Delete button when we aren't on the head of branch.
