### ISSUE TITLE
when are notifications sent?

### ISSUE THREAD

**Issue by kosli** [takezoe/gitbucket#883]
Should notifications for issues be sent out only to users that are involved with that issue (e.g. assigned or participant), or to everyone that is a collabortator of the repo? 

I have to add that the repo is in a group, and the collaborators that are in this group ( & repo), but NOT involved in the issues do receive also emails. At least for "new issues".

**Comment by kosli** [comment]
or is it at least possible to disable the notifications for specific memebers of the group & repo?

**Comment by takezoe** [comment]
GitBucket sends issues & pull requests notification email to the repository owner, collaborators and participants. This behavior is following GitHub.
