### ISSUE TITLE
ldap groups

### ISSUE THREAD

**Issue by natxo** [takezoe/gitbucket#885]
is it possible to couple ldap groups of users to gitbucket? That way new members could automatically be authorized to repositories instead of having to first login and then added to the repository.

**Comment by takezoe** [comment]
Sounds good. However, the current version of GitBucket does not have such feature. And also we do not have a plan to provide it in the near future because we do not have enough resources to improve LDAP support currently.

**Comment by takezoe** [comment]
Close all questions. If you have any questions about GitBucket, please send them to [the gitter room](https://gitter.im/takezoe/gitbucket) instead of issue according to [the Guideline for Issues](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md).
