### ISSUE TITLE
IIS HeliconZoo with PullRequestBuilder Not working

### ISSUE THREAD

**Issue by FlYnN91** [takezoe/gitbucket#887]
Hi all,

I've got GitBucket running on Windows IIS with no problems. I've used the Wiki setup HeliconZoo and it did the job. Currently I access my instance by http://host/gitbucket and there is no issue. However, i've setup the GitHub Pull Request Builder using the Wiki again and it really wants to work but I've found that because of the context_path set to "/gitbucket" the plugin trips out.
In Jenkins project the Github Project path is set to http://domain/gitbucket/Utilities/UniversalTestApplication/. The request plugin thinks that the "/gitbucket/" part is the owner and it cant find repository "Utilities", but it isn't, its just the context path set by HeliconZoo. I've tried changing the Context_path but no success. If I set it to "/", gitbucket generates a query string so long that IIS can't handle it and throws error 404.15

My questions are: Does any one know how I could change IIS or HeliconZoo configuration to allow me to access the instance without the "/gitbucket", or what could I change in the Pull Request Builder setup so it ignores the "/gitbucket".

Thanks

**Comment by takezoe** [comment]
Are there someone who are using GitBucket on IIS?

**Comment by FlYnN91** [comment]
I have solved my issue.
What I've done:
* In IIS HeliconZoo configuration comment variables CONTEXT_PATH, WAR_EXTRACT_PATH, CONTEXTS_DIR.
* In gitbucket.conf change base url from http://domain/gitbucket to http://domain/
* Restart IIS web application
