### ISSUE TITLE
Allow passwords longer than 20 characters

### ISSUE THREAD

**Issue by zovt** [takezoe/gitbucket#888]
Why is there even a limit?

**Comment by violentinternet** [comment]
I can't remember the name of the apps, but there were a couple of security advisories last year regarding this. One could set an arbitrary long password to the application and let the hashing function consume all the cpu creating a DoS situation. Imagine your password is one trillion chars long and the app will try to calculate the hash of it. So it makes sense to set an upper limit. 

But the limit should be much higher like you said, imho. In the era of password managers around 200 makes sense in my mind. Higher?

**Comment by takezoe** [comment]
This issue has been already raised in #118.
