### ISSUE TITLE
Can't log when using nginx reverse proxy with gitbucket on tomcat

### ISSUE THREAD

**Issue by fistons** [takezoe/gitbucket#889]
Hi,

I have installed gitbucket on tomcat8 (with something like that: http://exemple.org:8080/gitbucket) and I use nginx reverse proxy (to access it with http://git.exemple.org)

I can log in with http://exemple.org:8080/gitbucket but not with http://git.exemple.org: when I do that, it seems it simply reload the page.

I try to change the base url in the gitbucket.conf, without sucess.

What can I do?

here is my nginx configuration

    server {
        server_name git.exemple.org;

        location / {
            proxy_pass              http://localhost:8080/gitbucket/;
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout   150;
            proxy_send_timeout      100;
            proxy_read_timeout      100;
            proxy_buffers           4 32k;
            client_max_body_size    500m; # Big number is we can post big commits.
            client_body_buffer_size 128k;
        }

         location /assets/ {
            proxy_pass              http://localhost:8080/gitbucket/assets/;
            proxy_cache             cache;
            proxy_cache_key         $host$uri$is_args$args;
            proxy_cache_valid       200 301 302 1d;
            expires                 1d;
        }
    }

**Comment by takezoe** [comment]
Do you set `http://git.exemple.org` as the base url? You can set it at the system administration page.

**Comment by fistons** [comment]
Yes, I tried to set the base url and I have the same issue

**Comment by takezoe** [comment]
Check `action` attribute of the sign-in form. Is that `http://git.exemple.org/signin`?
If true, it's not configuration problem of reverse proxy.

**Comment by fistons** [comment]
Yes, the action is http://git.exemple.org/signin

**Comment by takezoe** [comment]
Hmm... All things seem correct. You might be possible to get some hints by checking request and response using Chrome Developer Tools.

**Comment by fistons** [comment]
I already check with Firebug and everything seems to be correct, http://git.exemple.org/signin return a 302 found http response. Maybe could I have a log from gitbucket somewhere?

**Comment by takezoe** [comment]
GitBucket outputs logs into stdout in default. You can find them in `catalina.out`.

**Comment by fistons** [comment]
There is nothing in `catalina.out`. I tried with the new 3.6 release with the same result

**Comment by takezoe** [comment]
I can't find a reason of your problem. It's working with same configuration as yours on my server.

**Comment by officer** [comment]
It seems to be a problem of cookie path.
try this configuration.

proxy_cookie_path /gitbucket/ /;

**Comment by fistons** [comment]
Thanks @officer , this was the problem. Now everything works great!

Thanks again!
