### ISSUE TITLE
can't use html tags in markdown

### ISSUE THREAD

**Issue by Eivy** [takezoe/gitbucket#899]
markdownファイルの中でhtmlタグを利用したいのですが、GitBucketで表示するとすべて削除されます。  
GitBucketではhtmlタグは使えないのでしょうか?

**Comment by officer** [comment]
I rewrite his question in English as below.

"""
I want to use HTML tags in .md files.
but, GitBucket will remove these tags.

Can't I use HTML tags in .md files on GitBucket?
"""

2015年9月8日火曜日、Eivy<notifications@github.com>さんは書きました:

**Comment by McFoggy** [comment]
@officer thanks for the translation !

**Comment by Eivy** [comment]
@officer thanks

**Comment by takezoe** [comment]
@Eivy In the current version of FitBucket, all html tags are removed to avoid security issue. But we might introduce whitelist based HTML tag rendering in the future.

**Comment by Eivy** [comment]
I see. I expect the feature.

**Comment by kurdtpage** [comment]
It would be really good to have something like this (look familiar?):
![capture](https://user-images.githubusercontent.com/1308716/33400245-45a95a9c-d5ba-11e7-9b41-a80ecddef3b6.PNG)

A viable alternative is something like [tinyMCE](https://www.tinymce.com/) which can be used for applications such as this

**Comment by takezoe** [comment]
@kurdtpage Do you mean the toolbar to decorate markdown? or TinyMCE like WYSIWYG editor?

**Comment by kurdtpage** [comment]
Currently it's just an empty `<textarea>`, ideally a WYSIWYG editor would be good, but at the very least a toolbar. I have to constantly lookup the [markdown cheat sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) when I'm replying to issues. I realise there is the Preview tab, but an inline editor like tinyMCE would do away with the two tabs and let you add comments in the way you want them. The editor creates a safe `<iframe>` so you wouldn't need to filter html tags

**Comment by demon101** [comment]
+1

**Comment by takezoe** [comment]
I like Markdown because we can edit it as plain text. Anyway, A toolbar and help are helpful for beginners. First of all I would like to consider adding them.
