### ISSUE TITLE
Commit messages do not translate to comments in issues

### ISSUE THREAD

**Issue by mkonersmann** [takezoe/gitbucket#900]
Since a while now, my gitbucket does not create comments when I reference issues in commit messages.
E.g. when a commit message says: "Fixed #20", It neither closes issue #20, nor adds the commit as a comment to the issue. 

Interestingly, when I look at the news stream on the page after logging in, the commit messages do not carry links to issues (the "#20" in this case is not a link).
On the other hand, when I look at a specific commit, the same commit messages carries a link to issue 20.
And when I look at the repository (the "Code" tab), the commit message of the last commit also carries a link.

Sadly, I don't know at which change that happened. It might have been with the change from 3.4 to 3.5, but that is not sure.

**Comment by imeszaros** [comment]
The same problem exists at my gitbucket installation. From the sources i found out that closing only works when you push the the commit to master (the default branch in the gitbucket config), and afaik i understood correctly, if you push it to another branch you wont be able to close the issue with a merge to master.

As far as i can tell it works quite randomly. Yesterday i created two hotfix branches from master, merged them back to develop and master, and pushed them to gitbucket. Comments were successfully created for both issues, but only one of them has been closed by gitbucket.

Then i merged a feature branch with commits supposed to close about 50 issues, none of them was closed, neither comments were created.

The links in commit messages to each issue works perfectly though.

**Comment by mkonersmann** [comment]
Thanks for your comment, @imeszaros.
In my use case, I only have commits to the master branch.

**Comment by takezoe** [comment]
@mkonersmann Thanks for your feedback. This is a bug, but I think already fixed in a3daf13c15526f37d48b7de04dba89a7d49c5ee1. Please wait for the next release!
