### ISSUE TITLE
gitbucket stops responding after being idle

### ISSUE THREAD

**Issue by FlYnN91** [takezoe/gitbucket#902]
Hi,

We have noticed that when the server is not getting used or no requests are sent to it for some time, it stops responding (no ssh, no git client access) just says request refused. The only to way to wake it up is to go to the server using a web browser. Has anyone experienced similar behavior? Our system runs on Windows 2012 Server IIS.

Thanks

**Comment by McFoggy** [comment]
I didn't noticed that on my setup: java -jar execution of gitbucket + nginx in front.

**Comment by EuVan** [comment]
I have same issue on Win Server 2008 R2 and IIS

**Comment by AlexTGM** [comment]
Also encountered similar behavior. Is this planned to be fixed?

**Comment by takezoe** [comment]
Close all questions. If you have any questions about GitBucket, please send them to [the gitter room](https://gitter.im/takezoe/gitbucket) instead of issue according to [the Guideline for Issues](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md).
