### ISSUE TITLE
Release 3.6 "Could not find or load main class JettyLauncher"

### ISSUE THREAD

**Issue by syco** [takezoe/gitbucket#903]
Hi,
I'm not compiling the source myself, instead I use the release provided.
Version 3.5 works perfectly, while version 3.6 terminates with that error.
Here's the jre version I'm using
```
# java -version
openjdk version "1.8.0_60"
OpenJDK Runtime Environment (build 1.8.0_60-b24)
OpenJDK Server VM (build 25.60-b23, mixed mode)
```

I don't know what can be useful to debug the problem, let me know if you need more informations.
Thanks.

**Comment by McFoggy** [comment]
I just re-downloaded le 3.6 release to be sure and executed: `java -jar gitbucket.war`

Everything works as expected for me.

MANIFEST.MF is good
![image](https://cloud.githubusercontent.com/assets/1119660/9760141/c4e17d06-56f2-11e5-9abc-e97caa614e8e.png)

The war contains the expected java class
![image](https://cloud.githubusercontent.com/assets/1119660/9760149/dec321ca-56f2-11e5-9226-bcabccf2845e.png)

How do you launch gitbucket?

**Comment by syco** [comment]
I start it with java -jar /opt/gitbucket.war
but I've re-downloaded the war file and it works now.
I've compared the checksum of the files and the old one was different:
    $ md5sum gitbucket*
    9beb084b64d596cbfc9d6618d743a7a7  gitbucket_3.6.war
    519921353dfd8fcd4b3936f14e344df2  gitbucket_error.war
I think the file was corrupted, but I would have expected java to throw some more specific error.
Sorry for the waste of time.
