### ISSUE TITLE
ssh publickey from LDAP

### ISSUE THREAD

**Issue by ccskoba** [takezoe/gitbucket#910]
LDAP server can provide user ssh publickey as sshPublicKey attribute.
it convenient, if PublicKeyAuthenticator support find publickey from LDAP.

I tried modify gitbucket and success it for me.
[ccskoba/gitbucket#30d054f43c](https://github.com/ccskoba/gitbucket/commit/30d054f43c9a2193d2878ced75bb554f442da9c5)

I did,
+ add "SSH Public key attribute" field on System Setting LDAP section.  
usually put "sshPublicKey"
+ change PublicKeyAuthenticator
+ add some method LDAPUtil

please advise these codes are effectual?

Thank you.

![pubkeyfromldap](https://cloud.githubusercontent.com/assets/11532107/9954602/65a14b84-5e25-11e5-9aba-be8947da60dc.jpg)

**Comment by McFoggy** [comment]
Hi, in order to ease tracking/reviewing/seeing it correctly could you branch & open a pull-request?

**Comment by takezoe** [comment]
Merged with #911
