### ISSUE TITLE
NotFound after online file editing for files which include space

### ISSUE THREAD

**Issue by budehuc** [takezoe/gitbucket#914]
GitBucket 3.6です。

Web上で直接、半角スペースが入ったファイル名のファイルを「Edit」し「Commit changes」すると、遷移後のページが「Not Found」になります（Commit自体は成功）。
URLが正しくないのが原因であると思いますが、回避方法はありますでしょうか。

**Comment by takezoe** [comment]
英語圏の方が多いのでタイトルだけ英語に変更させていただきました。問題自体はすでに4c149cf01ced49746307536452c781834c79dee0で修正されており、3.7のリリースに含まれる予定です。

**Comment by budehuc** [comment]
タイトル修正、そして重複の問題報告、失礼致しました。
3.7のリリースを楽しみにしております。
