### ISSUE TITLE
GitBucket didn't respond to all requests suddenly

### ISSUE THREAD

**Issue by TomMurakami** [takezoe/gitbucket#916]
takezoe様

お世話様です。
tomと申します。

昨日gitbucketにおいて、突然全てのリクエストに応答しなくなる現象が発生し、
gitbucketの再起動で改善しました。
問題が起きたのは18:30頃のようで、その時のログは下記内容になります。
----------------------------------------------------------------------------------------------------------------------------------------
18:28:08.877 [pool-2-thread-2] INFO  o.a.s.server.session.ServerSession - Server session created from /172.16.9.61:61635
18:28:08.877 [pool-2-thread-3] INFO  o.a.s.server.session.ServerSession - Kex: server->client aes128-ctr hmac-md5 none
18:28:08.877 [pool-2-thread-3] INFO  o.a.s.server.session.ServerSession - Kex: client->server aes128-ctr hmac-md5 none
18:30:08.986 [pool-1-thread-1] INFO  o.a.s.server.session.ServerSession - Disconnecting: Session has timed out waiting for authentication after 120000 ms.
----------------------------------------------------------------------------------------------------------------------------------------

何か原因として考えられることはありますでしょうか。

以上、よろしくお願い致します。

**Comment by takezoe** [comment]
@TomMurakami 海外のユーザの方がなるべく敷居の高さを感じないよう、少なくともIssueの一覧に日本語が載るのは避けたいと考えていますのでタイトルは英語に書き換えさせていただきました。日本語でのサポートが必要でしたらgitterに[日本語のチャットルーム](https://gitter.im/takezoe/gitbucket_ja)もありますのでこちらもご利用下さい。

ログはSSHD（Apache MYNA）が出力しているもののようですが、いただいた情報だけではちょっと判断できないです。クリティカルな用途にご利用であれば、その時点でのサーバのリソースがどうなっていたかなど把握できるようきちんと監視を入れておくとよいと思います。また、データのバックアップも定期的に行っておくことをおすすめします。

**Comment by TomMurakami** [comment]
takezoe様
We very rude.
This matter the cause identified the difficulty likely, please consider it as close did therefore in outline improvement in the service restart.
The future will be happy to use the Japanese chat room.
Thank you.
-----------------------------------------------------------------------------------------------------------
大変失礼いたしました。
本件は原因特定が難しそうで、一先ずサービス再起動で改善しましたのでクローズとさせてください。
今後は日本語チャットルームを利用させていただきます。
ありがとうざいました。

**Comment by McFoggy** [comment]
@takezoe it would be cool for the community if you could insist in next release announcement on the necessity to share information in English. I am sure the problem @TomMurakami faced could have been of some interest for other non Japanese speakers.

**Comment by takezoe** [comment]
@McFoggy Thanks, I added [CONTRIBUTING.md](https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md) and notation to [README.md](https://github.com/takezoe/gitbucket#support). Also I will describe in the next release announcement to Japanese users.
