### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by MarcusMoeller** [takezoe/gitbucket#926]
I have tried to run Gitbucket on both, standalone and within Tomcat7. The overall performance is quite poor when it comes to the web interface. Switching pages takes quite a long time. While doing that the java process consumes a lot of CPU. Is there a way to debug this further or to tweak the setup for better performance?

**Comment by MarcusMoeller** [comment]
It seems to be especially slow on on dashboard/pulls and dashboard/issues

**Comment by takezoe** [comment]
Hmm... What's spec of your machine?
