### ISSUE TITLE
Image upload support in Wiki

### ISSUE THREAD

**Issue by FlYnN91** [takezoe/gitbucket#932]
Hi,

I am aware off issues #622 and #582, but those were raised when Gihub did not have the upload feature.
Would be great to have image upload to Wiki like github, https://help.github.com/articles/adding-images-to-wikis/

Thanks

**Comment by nazoking** [comment]
Can you upload image file to github's wiki ?
I think it help say that user can insert image link .image resource is exists on othre server or repository, not on wiki.

**Comment by McFoggy** [comment]
github, **for issues only**, stores automatically any asset (image, video, ...) that you drag & drop into the issue text on their cloud, thus making the asset available via some URL.

See : http://solutionoptimist.com/2013/12/28/awesome-github-tricks/

**Comment by takezoe** [comment]
Same issue #85 is already raised.
However, as @nazoking and @McFoggy are saying, GitHub does not support file uploading in Wiki. Therefore we don't give priority to this feature currently.
