### ISSUE TITLE
Bind to network interface

### ISSUE THREAD

**Issue by haarp** [takezoe/gitbucket#936]
Is it possible to have Jetty bind to a network interface instead of all of them? e.g. one could bind to the loopback interface, in case Gitbucket only runs behind a reverse proxy.

**Comment by emag** [comment]
Yes, it's possible. 
e.g. `java -jar gitbucket.war --host=localhost`

https://github.com/takezoe/gitbucket#installation

And, please read Guideline for Issues.

https://github.com/takezoe/gitbucket/blob/master/CONTRIBUTING.md

```
If you have any question about GitBucket, send it to gitter room before raise an issue.
https://gitter.im/takezoe/gitbucket
```

**Comment by takezoe** [comment]
@emag Thanks for your help.

**Comment by haarp** [comment]
Oh sorry, I didn't think CONTRIBUTING.MD would cover questions too.

And thanks for your answer. I did see the parameter in the README, but I didn't think it was what I was looking for. Maybe you could consider renaming it? "host" makes me think of other things than interface binding :)

**Comment by emag** [comment]
> Oh sorry, I didn't think CONTRIBUTING.MD would cover questions too.

Ah, I should have mentioned the following link. Of course, README.md is covered it too :)
https://github.com/takezoe/gitbucket#support

> Maybe you could consider renaming it?

Hmm. Personally speaking, it's natural parameter name for me...

**Comment by takezoe** [comment]
@haarp Since, Previously, Issues had been filled by questions from newbies such as about installation or configuration, added guideline about usage of issues.

The parameter name `host` is came from embedded Jetty property name. It might be better to add usecase of this parameter to README.
