### ISSUE TITLE
gitbucket does correctly use --port parameter

### ISSUE THREAD

**Issue by McFoggy** [takezoe/gitbucket#942]
Tested on 3.7, launch gitbucket via `java -jar gitbucket.war --port=9090`

Open your browser on http://localhost:9090.
The gitbucket homepage is rendered with many errors because most URLs use a bad port number of 8080.

**Comment by pinghe** [comment]
review config file:   Base URL param
check whether the parameters are correct

**Comment by takezoe** [comment]
@McFoggy Did you set `http://localhost:8080` as base url as @pinghe mentioned?

**Comment by McFoggy** [comment]
Sorry you're right I didn't changed it. I launched a second instance to test upgrade to 3.7 and didn't thought I need to change that settings.
Sorry for disturbance.
